siderolabs/omni

frontend/src/views/omni/Overview/Overview.vue
So that users can join a vanilla Talos to Omni by applying this machine configuration.
Closes siderolabs/omni#171.
=> feat: add button to overview page to download partial machine config

frontend/package.json, frontend/src/views/omni/Overview/Overview.vue
To make it show recent instead of the oldest.
Fixes: https://github.com/siderolabs/omni/issues/194
=> fix: invert the order of recent clusters

.secrets.yaml, hack/generate-certs.example.yml, hack/test/integration.sh
Store client ID and domain encrypted.
=> chore: use new Auth0 app for CI

internal/backend/runtime/omni/controllers/omni/schematic_configuration.go, internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go
1 rule is enabled currently: when the node was ever running 1.5.x it will always have `bnx` and `intel` extensions installed.
Fixes: https://github.com/siderolabs/omni/issues/178
=> feat: automatically pick up extensions when upgrading Talos

frontend/src/router/index.ts, frontend/src/views/omni/Settings/BackupStorage.vue, frontend/src/views/omni/Settings/Settings.vue, frontend/src/views/omni/SideBar.vue, frontend/src/views/omni/Users/Users.vue, hack/test/integration.sh, internal/e2e-tests/main_test.go
Use two tabs on that page: `Users`, `Backups`.
Fixes: #12
=> feat: unify admin settings under `Settings` page

frontend/src/views/cluster/Nodes/NodeExtensions.vue
Also highlight the text and fix the spinner position.
=> fix: make search work on `NodeExtensions` page

frontend/src/components/common/Button/TButtonGroup.vue, frontend/src/components/common/Icon/TIcon.vue, frontend/src/components/common/TInput/TInput.vue, frontend/src/modal.ts, frontend/src/states/cluster-management/index.ts, frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue, frontend/src/views/omni/Modals/ConfigPatchEdit.vue, frontend/src/views/omni/Modals/MachineSetConfigEdit.vue
Allow setting update and delete strategies along with max parallelism.
Fixes: https://github.com/siderolabs/omni/issues/27
=> feat: implement the UI for adjusting machine sets update strategies

internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler.go
This check doesn't make sense for the config updates. We are trying to address the case when the config has broken the API server and you try to revert it. All api servers are down and you can not revert it because all api servers are down.
Fixes: #239
=> fix: do not block machine config updates if loadbalancer is down

client/pkg/omnictl/internal/access/client.go
Fixes: https://github.com/siderolabs/omni/issues/148
=> feat: warn about using `omnictl` version different from the backend

frontend/src/components/common/Labels/Labels.vue, frontend/src/views/omni/ItemLabels/ItemLabels.vue
Fixes: https://github.com/siderolabs/omni/issues/136
=> fix: add the label when clicking outside of the input

.codecov.yml, .github/workflows/ci.yaml, .github/workflows/e2e-backups-cron.yaml, .github/workflows/e2e-scaling-cron.yaml, .github/workflows/e2e-short-cron.yaml, .github/workflows/e2e-templates-cron.yaml, .github/workflows/e2e-upgrades-cron.yaml, .kres.yaml, Dockerfile, Makefile, internal/frontend/frontend.go
Rekres should improve build times and report the additional node info in CI.
=> chore: enable codecov and rekres

.codecov.yml, .github/workflows/ci.yaml, .github/workflows/e2e-backups-cron.yaml, .github/workflows/e2e-scaling-cron.yaml, .github/workflows/e2e-short-cron.yaml, .github/workflows/e2e-templates-cron.yaml, .github/workflows/e2e-upgrades-cron.yaml, .kres.yaml, Dockerfile, Makefile, frontend/package.json, internal/frontend/frontend.go
See: https://github.com/siderolabs/kres/pull/404
=> chore: run rekres

internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go
Make the controller fail when deletion fails and keep the finalizer to make the controller retry.
=> fix: retry affiliate deletes

internal/pkg/siderolink/manager.go
=> enable ALPN for machine API

internal/pkg/machinestatus/handler.go, internal/pkg/machinestatus/handler_test.go
The timestamp can jump back and forths if the Talos node time is out of sync, so we might ignore proper events.
So instead of reading the timestamp from the event, use Omni server time at the point when the event comes to the system.
In the worst case we'll see the node going through several phases quickly.
=> fix: ignore MachineStatus events timestamps as they're not reliable

cmd/integration-test/pkg/tests/talos.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/helpers.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go, internal/backend/runtime/omni/controllers/omni/internal/task/task.go, internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/backend/runtime/omni/controllers/omni/machine_status_link_test.go, internal/backend/runtime/omni/controllers/omni/machine_status_test.go, internal/backend/runtime/omni/omni.go
This rewrite should improve performance of the controller drastically. Fixes: https://github.com/siderolabs/omni/issues/281
=> chore: rewrite `MachineStatus` to use `QController`

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
The test `TestSchematicChanges` was flaky, as it was doing the following:
1. Trigger one or more `factory.talos.dev` build image generations & talos node upgrades by modifying resources
2. Capture these upgrade calls
3. Assert the build image in these calls (to be one or more with, always the expected image)
4. Clear captured upgrade calls
5. Trigger one or more `ghcr.io` build image generations & talos node upgrades by modifying resources
6. Capture these upgrade calls
7. Assert the build image in these new calls (to be one or more with, always the expected image)
The problem was, between step 4 and 7, an old `factory.talos.dev` build image could sometimes still be captured due to the nature of controllers asynchronously reconciling resources.
Replace this logic by not clearing the …
=> test: fix flaky test in `ClusterMachineConfigStatus` unit tests

internal/backend/runtime/cosi/cosi.go
Should fix nil reference errors.
=> fix: properly delete the item from the cached items slice

internal/backend/runtime/omni/omni.go, internal/backend/runtime/talos/talos.go
Safety net against any bugs there.
=> fix: handle panics in Omni and Talos UI watches

internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
Do not exit the loop, but just ignore such machines. Otherwise we don't create `ClusterMachineTalosVersion` resources for all new machines in the machine set, which blocks
`ClusterMachineConfigController` and the machines are not configured.
=> fix: skip invalid machines in `TalosUpgradeStatusController`

frontend/src/views/omni/Extensions/ExtensionsPicker.vue, frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Fixes: https://github.com/siderolabs/omni/issues/380
=> fix: display descriptions when show description checkbox is clicked

cmd/integration-test/pkg/tests/backup.go
The main problem with this test is that two backups can be created within the same second. It doesn't happen often,
but when it happens it results in the situation where we have "newer" backup overwriting the "old" one. We can protect
against that for local storage, but S3 doesn't support "If-None-Match" header yet.
In practice, it shouldn't matter if manual backup overwrites automatic one because we are interested in what's inside and
not what triggered it. Also, it's quite hard to hit the same time using API, we are only hitting it because we are enabling
automatic backups and immediately try to do a manual backup.
Closes #302
Finally.
=> fix: redo EtcdManualBackupShouldBeCreated

frontend/src/components/common/Icon/TIcon.vue, frontend/src/methods/machineset.ts, frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue, frontend/src/views/cluster/ClusterMachines/MachineSet.vue
Fixes: https://github.com/siderolabs/omni/issues/387
=> feat: provide cleaner UI for the machine sets/machines lists

client/pkg/template/internal/models/list.go, client/pkg/template/operations/delete.go, internal/backend/runtime/omni/omni.go
Use slices.Insert and slices.Concat where it's proper.
=> chore: replace append with slices pkg functions

frontend/src/components/THeader/THeader.vue, frontend/src/components/common/Button/TButton.vue, frontend/src/components/common/Icon/TIcon.vue, frontend/src/components/common/OngoingTasks/OngoingTasks.vue, frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue, frontend/src/views/cluster/ClusterMachines/MachineSet.vue
Fix the bug with the icons displayed smaller than their width and height values.
Adjust style of the header a bit: colors, transitions and small screen display.
=> fix: do better handling of small screens

frontend/src/components/TModal.vue, frontend/src/views/cluster/ClusterMachines/MachineSet.vue, frontend/src/views/omni/Modals/UpdateKubernetes.vue, frontend/src/views/omni/Modals/UpdateTalos.vue, go.mod, go.sum
Also adjust Talos and Kubernetes upgrade modal windows height to occupy all vertical space - padding.
Fixes: https://github.com/siderolabs/omni/issues/391
=> feat: show `N/∞` in the machine set if unlim allocation policy is used

internal/backend/runtime/omni/state_validation.go, internal/backend/runtime/omni/state_validation_test.go
If the machine set is empty, it should be possible to switch its management mode between machine class mode and manual.
Closes siderolabs/omni#390.
=> fix: allow changing machine set node mgmt mode if it has no nodes

Makefile, internal/backend/grpc/router/router.go, internal/backend/server.go
Fixes: https://github.com/siderolabs/omni/issues/432
=> fix: properly clean up stale Talos gRPC backends

deploy/compose.yaml, deploy/env.template
Updated the to allow the sample compose deployment example to work more easily based off testing in my lab environment and ongoing usage
=> Update to compose deployment example to match and include tun requirement

client/go.mod, client/go.sum, go.mod, go.sum, internal/backend/grpc/grpc.go, internal/backend/runtime/omni/omni.go, internal/backend/server.go
This affects Get/List operations, but not Watch and Create/Update/Destroy.
=> fix: provide cached access to the state via Omni API

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
This check in the `ClusterMachineConfigStatus` controller is incorrect: there's no relation between the `MachineStatus` update and the machine connectivity.
We should have another way to re-trigger reconciliation and one of the options is the requeue after.
Make it re-queue the reconciliation limited amount of times. It's not 100% fail-proof, but no worse than before.
=> fix: do not rely on `MachineStatus` updates when checking maintenance

frontend/src/components/common/Icon/TIcon.vue
=> fix: properly display icons on Safari browser

internal/backend/runtime/omni/controllers/omni/machine_class_status.go, internal/backend/runtime/omni/controllers/omni/machine_set_node.go
The controller should add finalizer on the `MachineSetRequiredMachines` otherwise it will miss the deletion.
=> fix: use proper finalizer chain in the `MachineClassStatusController`

internal/backend/runtime/omni/controllers/omni/cluster_machine_identity.go
The code had the bug which was leading to not removing the old labels from the resource and not resetting the etcd member.
=> fix: properly update `ClusterMachineIdentity` resource

internal/backend/runtime/omni/export_test.go, internal/backend/runtime/omni/omni.go, internal/backend/runtime/omni/state_validation.go, internal/backend/runtime/omni/state_validation_test.go
Fixes: https://github.com/siderolabs/omni/issues/431
=> fix: do not allow deleting machine classes which are used anywhere

go.mod, go.sum
See: https://github.com/cosi-project/state-etcd/pull/158
=> chore: bump state-etcd module version

internal/backend/runtime/omni/controllers/omni/data/kube-service-exposer-config-patch.tmpl.yaml
See: https://github.com/siderolabs/kube-service-exposer/pull/9
=> chore: bump kube-service-exposer version

cmd/integration-test/pkg/tests/stats.go, cmd/integration-test/pkg/tests/tests.go, cmd/integration-test/root.go, hack/compose/docker-compose.yml, hack/compose/prometheus/prometheus.yml, hack/test/integration.sh
Make the tests fail if the metrics do not meet the expected thresholds.
=> test: run prometheus in tests and check metrics after talemu tests

internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
The controller should have InputDestroyReady input for the ExposedServiceType and the tracker should skip resources in the tearingDown phase.
=> fix: properly handle ExposedService resource finalizers

internal/backend/runtime/omni/controllers/omni/redacted_cluster_machine_config.go
Unmarshalling/marshalling machine configs (especially if it is large) is consuming lots unnecessary resources.
=> fix: skip reconciling redacted machine config on no input changes

internal/backend/runtime/kubernetes/kubernetes.go, internal/backend/runtime/talos/clients.go
Fixes #526
More details in comments.
=> fix: increase LRU cache size for Talos and Kubernetes clients

internal/backend/grpc/grpc_test.go, internal/backend/grpc/schematics_test.go, internal/backend/runtime/omni/controllers/omni/cluster_loadbalancer_test.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_status_test.go, internal/backend/runtime/omni/controllers/omni/loadbalancer_test.go, internal/backend/runtime/omni/controllers/omni/machine_set_etcd_audit_test.go, internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go, internal/backend/runtime/omni/controllers/omni/omni_test.go, internal/backend/runtime/omni/controllers/omni/secrets_test.go
Should make CI runs more reliable.
=> test: fix several flaky tests

internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
The controller was missing to remove some `ExposedService`s, because the code path triggered by the `DestroyReady` phase input did not reach any cleanup code.
Rework the `ExposedService` cleanup code slightly to also remove the `DestroyReady` resources.
=> fix: properly cleanup tearing down exposed services

README.md, client/README.md, frontend/src/components/THeader/THeader.vue, frontend/src/views/cluster/Backups/BackupsList.vue
=> docs: update doc urls

internal/backend/runtime/omni/state.go
Small PR to test that e2e-scaling and e2e-upgrades tests still work.
=> chore: print error on closing secondary storage backing store

client/pkg/client/encoding.go, internal/backend/grpc/router/encoding.go
Use it for both client and server gRPC.
=> chore: enable 'github.com/planetscale/vtprotobuf' encoding

internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status.go, internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status_test.go
The controller wasn't removing the finalizers from tearing down `ClusterMachineStatus` resources if the workload proxy feature is disabled.
Make the controller always loop through the statuses and remove finalizers.
Fixes: https://github.com/siderolabs/omni/issues/583
=> fix: always remove finalizers from the `ClusterMachineStatus`

frontend/src/views/omni/Machines/MachineItem.vue
=> fix: spelling for hover text

frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue, frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue
Use proper var names and fields in the UI for cluster machine list and machine set config.
=> fix: get rid of the exceptions in the ui

.github/workflows/ci.yaml, .github/workflows/e2e-backups-cron.yaml, .github/workflows/e2e-scaling-cron.yaml, .github/workflows/e2e-short-cron.yaml, .github/workflows/e2e-templates-cron.yaml, .github/workflows/e2e-upgrades-cron.yaml, .github/workflows/e2e-workload-proxy-cron.yaml, client/pkg/infra/controllers/provision.go, client/pkg/infra/provision/context.go, client/pkg/infra/provision/errors.go, frontend/src/components/common/Form/ContentWrapper.vue, internal/backend/runtime/omni/controllers/omni/machine_provision.go, internal/backend/runtime/omni/controllers/omni/machine_request_set_status.go
MachineRequest is private in the provider context, so the provider data should be exposed through some method.
Also fix a couple of bugs in the infra provider common library.
=> chore: add a way to get provider data in the infra provider

internal/pkg/grpcutil/logger.go
- If there is no correct address in headers, but actual peer address is in correct IPv4/6 form, preserve it.
- Otherwise if there are error parsing headers set `peer.address` to the `<invalid_ip>`.
- Otherwise set it to the `<unknown_ip>`.
For #668
=> chore: set `peer.address` to inform about IP status

.github/workflows/ci.yaml, .kres.yaml, Dockerfile, Makefile
=> fix: do not build acompat docker image

internal/backend/runtime/omni/controllers/omni/versions.go
The fix will help to avoid issues with Omni having Talos versions without extensions, as Talos versions appear in ghcr.io registry before the image factory picks them up.
Fixes: https://github.com/siderolabs/omni/issues/661
=> fix: fetch Talos version from the image factory

frontend/src/views/cluster/Manifest/Sync.vue
It was encoding b64 string instead of decoding it.
Fixes: https://github.com/siderolabs/omni/issues/676
=> fix: properly show the current manifests in the bootstrap manifest sync

.dockerignore, Dockerfile
Fixes: https://github.com/siderolabs/omni/issues/714
=> fix: make web UI show favicon

client/pkg/infra/controllers/provision.go
The bug was causing missing reconciliations.
=> fix: properly map config patch requests in the infra provision ctrl

deploy/compose.yaml
Typo of SIDEROLINK_WIREGUARD_ADVERTISED_ADDR
=> Update compose.yaml typo

internal/backend/extensions/extensions.go, internal/backend/extensions/extensions_test.go
Handle renamed drm extensions.
Fixes: https://github.com/siderolabs/talos/issues/9728
=> chore: handle renamed drm extensions

cmd/integration-test/pkg/tests/infra.go
As the bare-metal infra provider gets power management implemented, we assert the power state of the infra machines in the tests.
Part of https://github.com/siderolabs/omni/issues/768.
=> test: assert power on/off status in static infra provider tests

frontend/src/views/omni/Users/ServiceAccounts.vue
=> fix: do not disable create service account button for SAML mode

internal/backend/runtime/omni/controllers/omni/infra_machine.go, internal/backend/runtime/omni/controllers/omni/infra_machine_test.go
Improve the handling of extra mapped input finalizers in `InfraMachineController`, also add a finalizer to `MachineExtensions` resources.
=> fix: correctly handle input finalizers in `InfraMachineController`

internal/backend/runtime/omni/controllers/omni/machine_set_etcd_audit.go
The logic of the etcd audit got outdated with the more recent Talos versions. `apid` now runs in the states where it wasn't available before, so the check for the etcd member might lead to the false-positives.
Also reorder the `auditMember` check sequence to be more correct.
Fixes: https://github.com/siderolabs/omni/issues/750
=> fix: never remove etcd members which ID is discovered at least once

frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Fixes: https://github.com/siderolabs/omni/issues/175
=> fix: enable secure boot checkbox in the UI

client/pkg/omni/resources/omni/labels.go, frontend/src/api/resources.ts, frontend/src/methods/labels.ts, frontend/src/views/omni/ItemLabels/ItemLabel.vue, frontend/src/views/omni/ItemLabels/ItemLabels.vue, frontend/src/views/omni/ItemLabels/LabelsInput.vue
Fixes: https://github.com/siderolabs/omni/issues/822
=> fix: change the look of the infra provider labels

internal/backend/runtime/omni/infraprovider/state.go, internal/backend/runtime/omni/infraprovider/state_test.go
Found a couple of bugs in the infra provider state:
- For some reason, sometimes a resource update is detected where nothing other than the `.metadata.version` was changing. In these cases, the validation blocked the update. Fix this by ignoring the version field. Since we ignore the version field, we now compare the specs as well as the metadata.
- Infra providers were able to modify `infra.Machine` resources when they shouldn't have. The fix above also addresses that.
=> fix: fix immutability checks in infra provider state

.conform.yaml, .golangci.yml, LICENSE, client/.golangci.yml, cmd/omni/cmd/cmd.go, go.mod, go.sum, internal/backend/runtime/omni/controllers/omni/reporting.go, internal/backend/runtime/omni/controllers/omni/reporting_test.go, internal/backend/runtime/omni/omni.go, internal/pkg/config/config.go
Adds a controller for reporting machine count to Stripe.
=> feat: add Stripe machine reporting

client/pkg/client/example_test.go, cmd/integration-test/pkg/clientconfig/clientconfig.go, cmd/integration-test/pkg/tests/tests.go
Same as #897 but for tests and examples.
=> fix: don't forget to close grpc connections in tests

internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go, internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store.go
We create uploader each time anyway,
=> chore: remove unused field in `s3store.Store`

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Make `ClusterMachineConfigController` fail to apply the machine config
if the machine enters maintenance mode without Omni issuing the reset
command.
Fixes: https://github.com/siderolabs/omni/issues/922
=> fix: make the apply config fail if machine has wrong state

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go, internal/backend/runtime/omni/controllers/omni/omni_test.go
Implement an upgrade workaround for the Talos versions affected by https://github.com/siderolabs/talos/issues/10163.
Closes https://github.com/siderolabs/omni/issues/893.
=> fix: add workaround to stage upgrades for talos `v1.9.0-v1.9.2`

client/pkg/omnictl/talosconfig.go
If the cluster flag is provided and cluster is not found on the omni instance warn the user when retrieving taloscinfig via the `omnictl talosconfig` command.
fixes https://github.com/siderolabs/omni/issues/938
Please let me know if there's a better approach to fixing the issue or if it should error instead of printing a warning.
=> chore: warn if cluster doesn't exist in omnictl talosconfig command

internal/backend/runtime/omni/migration/manager.go
More information about how it's going amd what is done.
=> chore: add logging for migrations

internal/pkg/siderolink/provision.go
The problem with the previous approach is that any consequent node reboot will mess up the connection flow for the machines managed by the bare metal infra provider.
So in addition to allowing to join the nodes with the different join token for one time, reset the annotation on the link. Which makes the machine go to the uninstalled mode once again, until it is added to a cluster.
=> fix: remove force unique token annotation from the link on wipe

cmd/omni/cmd/cmd.go, internal/backend/runtime/omni/controllers/omni/cluster_bootstrap_status_test.go, internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/disabledstore.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/filestore.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/metrics.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/store.go, internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/export_test.go, internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store.go, internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store_test.go, internal/backend/runtime/omni/controllers/omni/secrets_test.go, internal/backend/runtime/omni/omni.go, internal/backend/runtime/omni/state_validation_test.go, internal/pkg/config/config.go
=> feat: add support for setting throughput for uploads and downloads

go.mod, go.sum, internal/pkg/siderolink/manager.go
Updated SideroLink module to add the support for it and configure it on the Omni side.
=> feat: validate incoming packets addresses in siderolink manager

internal/backend/resourcelogger/resourcelogger_test.go
The test was flaky - in some rare cases, the create/update times were not set as expected. Fix it, simplify and speed up the test using the new `synctest` experiment.
=> test: fix the timing related flake in resource logger test

client/pkg/omnictl/download.go, frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Make it more understandable and clear.
Closes https://github.com/siderolabs/omni/issues/1023.
=> fix: update text and description for SideroLink over GRPC

deploy/helm/omni/Chart.yaml, deploy/helm/omni/templates/deployment.yaml, deploy/helm/omni/values.yaml
Moves hard coded duplicated limits from deployment template to values for helm.
=> fix: duplicate resources declaration in helm deployment

frontend/src/components/common/TInput/TInput.vue, frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanelCondition.vue, internal/backend/runtime/omni/pkg/check/etcd.go
Fixes: https://github.com/siderolabs/omni/issues/1020
=> fix: show warning instead of error for etcd quorum being at min

frontend/src/views/omni/Modals/ClusterDestroy.vue
Fixes: https://github.com/siderolabs/omni/issues/862
=> fix: ignore 404 errors when removing disconnected links of a cluster

client/pkg/omni/resources/omni/cluster_status.go, frontend/src/components/common/List/TList.vue, frontend/src/views/omni/Clusters/Clusters.vue
Fixes: https://github.com/siderolabs/omni/issues/819
=> feat: support filtering clusters by readiness

frontend/src/components/common/CodeEditor/CodeEditor.vue, frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue, go.mod, go.sum
Also fix the alignment of the elements in the cluster machine item.
=> fix: use proper background for the sticky window in the code editor

cmd/integration-test/pkg/tests/workload_proxy.go, internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler.go
Yet another fix to exposed services: for the brand new exposed services, we wrongly assumed that they already had an alias generated. Fix this by checking if they already have an alias.
=> fix: fix existing alias check for exposed services

internal/backend/runtime/omni/controllers/omni/config_patch_cleanup.go, internal/backend/runtime/omni/controllers/omni/config_patch_cleanup_test.go, internal/backend/runtime/omni/controllers/omni/internal/configpatch/configpatch.go
Check all labels, and treat as orphaned if all labels say it's orphaned.
=> fix: config patch cleanup

internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
=> fix: use correct version contract for machine config generation

client/pkg/omni/resources/omni/annotations.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go, internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Backported PRs:
- https://github.com/siderolabs/omni/pull/1110
- https://github.com/siderolabs/omni/pull/1111
=> backports for 0.48.3

frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Fixes: https://github.com/siderolabs/omni/issues/1117
=> fix: correctly sort versions on the download installation media page

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
Test that config generation stays stable through the cluster lifecycle.
Prevent regressions like the ones in https://github.com/siderolabs/omni/issues/1095#issue-2993591967.
Closes https://github.com/siderolabs/omni/issues/1096.
```
--- PASS: TestClusterMachineConfigSuite (8.14s)
--- PASS: TestClusterMachineConfigSuite/TestConfigEncodingStability (8.14s)
--- PASS: TestClusterMachineConfigSuite/TestConfigEncodingStability/initial-1.2.1 (0.13s)
--- PASS: TestClusterMachineConfigSuite/TestConfigEncodingStability/initial-1.2.1/from-1.2.1-to-1.3.1 (0.02s)
--- PASS: TestClusterMachineConfigSuite/TestConfigEncodingStability/initial-1.2.1/from-1.3.1-to-1.4.1 (0.02s)
--- PASS: TestClusterMachineConfigSuite/TestConfigEncodingStability/initial-1.2.1/from-1.4.1-to-1.5.1 (0.01s)
--- PASS: …
```
=> test: add config encoding stability tests

client/pkg/access/serviceaccount.go, internal/backend/runtime/omni/controllers/omni/service_account_status.go, internal/backend/runtime/omni/controllers/omni/service_account_status_test.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
The suffix should be checked there, not prefix.
Also write the tests to verify service account status controller. Found couple more issues with the finalizers flow in the controller.
=> fix: properly detect infra provider service accounts

cmd/omni/cmd/cmd.go, cmd/omni/cmd/run.go, internal/pkg/config/config.go
This change will be used in the new integration tests.
=> chore: allow running Omni programmatically from other Go code

DEVELOPMENT.md
Add some points about the development setup on darwin.
=> docs: add guide for development on darwin

internal/pkg/logreceiver/logreceiver.go, internal/pkg/siderolink/manager.go
Refactor the siderolink manager to improve context handling for Wireguard and its associated services.
This ensures proper shutdown and cleanup of resources.
Add a linger option to TCP connections in the log receiver to allow the OS a grace period to close the connection.
Fixes: #1102
=> fix: gracefully handle logServer shutdown

frontend/.vscode/settings.json, frontend/package-lock.json, frontend/package.json, frontend/src/methods/index.ts, frontend/src/views/cluster/Nodes/NodeOverview.vue, frontend/src/views/cluster/Nodes/NodesList.vue, frontend/src/views/cluster/Nodes/components/NodesItem.vue, frontend/src/views/cluster/Pods/components/TPodsItem.vue, frontend/src/views/cluster/Pods/components/TPodsList.vue, frontend/src/views/omni/Modals/DownloadSupportBundle.vue
Update frontend dependencies. This should also address security vulnerability reports from dependabot.
=> chore: update frontend dependencies

frontend/src/api/watch.ts, frontend/src/components/common/OngoingTasks/OngoingTasks.vue, frontend/src/components/common/Watch/Watch.vue, frontend/src/components/common/Watch/useWatch.ts, frontend/src/views/cluster/Backups/BackupsList.vue, frontend/src/views/cluster/ClusterMachines/ClusterMachines.vue, frontend/src/views/cluster/Nodes/NodePatches.vue, frontend/src/views/cluster/Pods/TPods.vue, frontend/src/views/omni/Clusters/Clusters.vue, frontend/src/views/omni/Clusters/Management/ClusterScale.vue, frontend/src/views/omni/Extensions/ExtensionsPicker.vue, frontend/src/views/omni/MachineClasses/MachineClass.vue, frontend/src/views/omni/Machines/Machines.vue, frontend/src/views/omni/Modals/NodeDestroyCancel.vue, frontend/src/views/omni/Modals/RoleEdit.vue, frontend/src/views/omni/Overview/Overview.vue
Improve useWatch typings to be able to narrow to a single item instead of an array of items when the appropriate options are passed
=> chore: improve useWatch typings

frontend/src/views/omni/Home/HomeGeneralInformation.vue, frontend/src/views/omni/Modals/NodeDestroyCancel.vue
Fix copy buttons on omni home page.
Fixes #1495
=> fix: copy buttons on omni home page

frontend/src/components/common/Button/IconButton.vue, frontend/src/components/common/Button/TButton.vue
Improve TS typing for TButton by inheriting the base button props to account for [fallthrough attributes](https://vuejs.org/guide/components/attrs). Also removed currently unused attributes.
This can prevent issues like:
- https://github.com/siderolabs/omni/issues/1495
=> chore: improve tbutton typings

frontend/src/App.vue, frontend/src/views/cluster/Nodes/NodeDetails.vue, frontend/src/views/omni/Machines/Machine.vue, frontend/src/views/omni/Settings/Settings.vue
Fix certain routes not filling up available space
=> fix: route resizing issue

frontend/src/views/omni/Auth/Authenticate.vue, frontend/src/views/omni/MachineClasses/MachineClass.vue, frontend/src/views/omni/MachineClasses/MachineClasses.vue
Fix route view size on login and machine classes pages
=> fix: route size on login and machine classes

hack/test/integration.sh
the flag is being removed in talos
=> chore: remove the usage of --input-dir flag in tests

client/pkg/omnictl/jointoken.go
If no flags are set use the default token.
Fixes: https://github.com/siderolabs/omni/issues/1503
=> feat: support generating join configs with searching join tokens by name

frontend/src/views/omni/Home/HomeContent.vue, frontend/src/views/omni/Home/HomeGeneralInformation.vue
Fix error & loading states for the HomeGeneralInformation component
=> fix: home general info error & loading

frontend/src/views/omni/Modals/JoinTokenCreate.vue
Fix create join token missing a margin between the form and the create button
=> fix: create join token modal margin

frontend/package-lock.json, frontend/package.json, frontend/src/api/grpc.ts, frontend/src/api/options.ts, frontend/src/api/watch.spec.ts, frontend/src/components/common/CodeEditor/CodeEditor.vue, frontend/src/methods/key.ts, frontend/src/methods/logs.ts, frontend/src/views/cluster/Nodes/NodeMonitor.vue, frontend/src/views/cluster/Nodes/components/NodesMonitorChart.vue, frontend/src/views/omni/Auth/Authenticate.spec.ts, frontend/tsconfig.node.json, frontend/tsconfig.vitest.json, frontend/vite.config.ts, frontend/vitest.setup.ts
Test that SAML login redirect correctly forwards the query string
Tests the change in https://github.com/siderolabs/omni/pull/1599
Blocked by: https://github.com/siderolabs/omni/pull/1600
=> test: including query string for saml login

.dockerignore, Dockerfile, frontend/msw/index.ts, frontend/package-lock.json, frontend/package.json, frontend/src/api/watch.spec.ts, frontend/tsconfig.node.json, frontend/tsconfig.vitest.json, frontend/vitest.setup.ts
Introduce [MSW](https://mswjs.io/) to mock API calls at the network level, so that we can test more easily and closer to reality
Related PR
- https://github.com/siderolabs/kres/pull/574
=> test: introduce msw to mock api calls

frontend/src/components/common/List/ListItemBox.vue, frontend/src/components/common/List/TListItem.vue, frontend/src/components/common/SlideDownWrapper/TSlideDownWrapper.vue, frontend/src/views/cluster/Pods/components/TPodsItem.vue
Simplify TSlideDownWrapper to only focus on the sliding animation
=> refactor: simplify tslidedownwrapper

frontend/src/components/common/Status/TStatus.vue, frontend/src/views/omni/Settings/InfraProviders.vue
Fix the spacing of items in the InfraProviders list
=> fix(frontend): adjust spacing of items in infraproviders

internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
PRs backported:
- https://github.com/siderolabs/omni/pull/1671
=> backports: for v1.2.1

frontend/.storybook/preview.ts, frontend/msw/helpers.ts, frontend/msw/server.ts, frontend/src/api/watch.spec.ts, frontend/src/views/omni/Extensions/ExtensionsPicker.stories.ts, frontend/src/views/omni/Machines/MachinesPending.stories.ts, frontend/src/views/omni/Modals/MaintenanceUpdate.stories.ts, frontend/src/views/omni/Modals/UpdateKubernetes.stories.ts, frontend/src/views/omni/Modals/UpdateTalos.stories.ts
Simplify the way MSW handlers are created in storybook to reduce code repitition
=> refactor(msw): simplify msw handlers in storybook

frontend/msw/server.ts, frontend/src/components/common/Icon/TIcon.vue, frontend/src/components/icons/IconLocked.vue, frontend/src/components/icons/IconUnlocked.vue, frontend/src/router/index.ts, frontend/src/views/cluster/Nodes/NodeMounts.vue, frontend/src/views/omni/Clusters/ClusterItem.spec.ts, frontend/src/views/omni/Clusters/ClusterItem.vue, frontend/vitest.setup.ts
Fix locked icon not showing when cluster is locked
=> fix(frontend): fix locked icon not showing when cluster is locked

internal/backend/runtime/omni/controllers/omni/internal/kubernetes/versions.go, internal/backend/runtime/omni/controllers/omni/internal/kubernetes/versions_test.go, internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_status.go
Rely on the data prepared by versions controller.
=> refactor: use TalosVersion compatibility in Kubernetes upgrades
