siderolabs/omni

frontend/package.json, frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Make the UI use proper data format for the machine labels meta value when generating the image on the `DownloadInstallationMedia` page.
=> fix: properly generate labels meta in the UI

client/go.mod, client/go.sum, go.mod, go.sum, internal/backend/runtime/omni/controllers/omni/talos_extensions.go, internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
Otherwise it can never find the version in the image factory versions response and always skips it.
=> fix: add missing `v` prefix when looking up version in the image factory

CHANGELOG.md, hack/release.toml, internal/version/data/tag
This is the official v0.30.1 release.
=> release(v0.30.1): prepare release

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
`ClusterMachineConfigPatches` resources of old clusters are missing label `omni.sidero.dev/machine-set` and the controller always thinks that the machines are not configured yet.
=> fix: get rid of the issue with `MachineSets` stuck in `Reconfiguring`

.conform.yaml, .github/workflows/ci.yaml, .github/workflows/e2e-backups-cron.yaml, .github/workflows/e2e-scaling-cron.yaml, .github/workflows/e2e-short-cron.yaml, .github/workflows/e2e-templates-cron.yaml, .github/workflows/e2e-upgrades-cron.yaml, Dockerfile, Makefile, internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go, internal/frontend/frontend.go
`ClusterMachineConfigPatches` resources of old clusters are missing
label `omni.sidero.dev/machine-set` and the controller always thinks
that the machines are not configured yet.
(cherry picked from commit https://github.com/siderolabs/omni/commit/5a8abf584edd605ac7bfc6f72b31142c857128c4)
=> fix: get rid of the issue with MachineSets stuck in Reconfiguring

frontend/src/components/common/ActionsBox/TActionsBox.vue, frontend/src/views/common/NodeContextMenu.vue, frontend/src/views/omni/Machines/MachineItem.vue
Machine UUID is used in many CLI commands, but there's no way to copy it from the UI quickly.
Fixes: https://github.com/siderolabs/omni/issues/28
=> feat: add the context menu for copying the machine id

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Simple fix to not skip updating Talos if the machine schematic is empty.
Verified that on a cluster running on the nodes with the invalid schematics. Upgrades work.
=> fix: properly handle upgrades for the machines with invalid schematics

internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
If no error occurs during pulling an image, do not gather it in multi-error, causing the task to be wrongly marked as failed.
=> fix: fix error handling in image pre pull task

internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go, internal/backend/runtime/omni/controllers/omni/machine_cleanup.go, internal/backend/runtime/omni/controllers/omni/machine_cleanup_test.go
This PR contains fixes for the following issues:
- When a `Link` resource was deleted, `MachineCleanupController` was unable to remove finalizers on the `MachineSetNode` resource, as it did not pass the correct owner `""` when calling `Teardown`.
- `ClusterMachineStatusController` not handling the cases where the matching `Machine` might be missing.
- `MachineSetController` not handling the cases where the `Machine` resource was missing for any of the `MachineSetNode`s that were tearing down.
The latter two fixes prevent clusters from getting stuck if they are in a state where there is a missing machine in their machine sets.
Closes #100, closes #97.
=> fix: prevent link and clustermachine deletion from getting stuck

frontend/src/components/common/TInput/TInput.vue, frontend/src/views/cluster/Nodes/NodeOverview.vue, frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Looks like `min-w-max` works differently there, so it messes up the layout.
Fixes: https://github.com/siderolabs/omni/issues/42
=> fix: properly render download installation media page in Safari

client/pkg/omni/resources/omni/config_patch.go, client/pkg/omni/resources/omni/config_patch_test.go
Add the new fields `cluster.acceptedCAs` and `machine.acceptedCAs`, which are introduced by Talos 1.7, to the list forbidden fields in config patches.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
=> feat: forbid `*.acceptedCAs` fields in config patches

internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go
The extension `modules.dep` is a virtual extension, used for the Kernel module dependencies. Therefore, it must not be used when computing the machine schematic - it causes a miscalculation, resulting in failing installer pull attempts from the image factory.
Closes #122.
=> fix: ignore `modules.dep` virtual extension on schematic id calculation

frontend/src/views/omni/Settings/BackupStorage.vue
Fixes: https://github.com/siderolabs/omni/issues/98
=> fix: add missing `region` input on the backups storage config page

internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler_test.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/operations.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/operations_test.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/reconciliation_context.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/reconciliation_context_test.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler_test.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/workers_handler_test.go
If the cluster is not found it's not critical for teardown flow, so we shouldn't skip reconcile in that case.
=> fix: ignore not existing cluster in `MachineSet` teardown flow

frontend/package.json, frontend/src/views/cluster/Config/Patches.vue, frontend/src/views/omni/Clusters/Management/ClusterCreate.vue, frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue, internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go, internal/backend/runtime/omni/state_validation.go
Make `MachineClass` selector skip them.
Disable them in the UI.
Do not allow adding them as the resources, validate on the backend level.
Fixes: https://github.com/siderolabs/omni/issues/46
=> feat: don't allow downgrades of the machines when adding to a cluster

internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go
Fix the wrong assertion in the controller. The test was flaky and was passing due to lucky timing.
=> test: fix assertion in maintenance config patch test

internal/backend/runtime/omni/controllers/omni/internal/machineset/operations.go, internal/backend/runtime/omni/controllers/omni/maintenance_config_patch.go, internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Empty config patches are detected as JSON6902 patches which are not supported by Omni and by the Talos machine config patcher when the config is multidoc.
Empty system-level config patches can be generated at the moment by `MaintenanceConfigPatchController`.
=> fix: skip empty config patches in `ClusterMachineConfigPatches`

internal/backend/runtime/omni/controllers/omni/export_test.go, internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go, internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
The controller code has the bug in the loop: the last fallback was picking resources which have cluster label, but the thing is that _all_ of them have it.
Make it select only the resources which have _only_ cluster label.
=> fix: properly select schematics for machine set and machine levels

go.mod, go.sum, internal/backend/runtime/omni/controllers/omni/installation_media.go, internal/backend/runtime/omni/controllers/omni/internal/boards/boards.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
This is compatibility code for SBCs running Talos < 1.7.x. With this change it's possible to do seamless upgrade of SBCs running without overlays.
Fixes: https://github.com/siderolabs/omni/issues/145
=> feat: generate overlay info by extracting board kernel args

cmd/integration-test/pkg/tests/cli.go, cmd/integration-test/pkg/tests/talos.go, internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
CLI tests were failing due to self signed certs in CI. Upgrade tests have issues with the machine versions after upgrade being started and then canceled. There's a slight delay of the update of the actual Talos version VS machine version.
=> test: get rid of upgrade test flakiness, fix cli tests

client/pkg/omni/resources/omni/cluster_machine_status.go, frontend/src/components/common/List/TList.vue, frontend/src/views/cluster/Nodes/NodesList.vue
Enable search for the `ClusterMachineHostname`.
Disable filtering by the node status, as it's not going to work in paginated mode for the data pulled from Kubernetes.
This should make the UI more responsive on the clusters with a huge amount of nodes.
=> fix: paginate nodes list page

frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue
The UI does not create install disk config patch if the user does not touch disk dropdown.
It works correctly if the default disk is shown initially there, then it works as intended.
But the bug was that we were showing the first install disk as the selected option instead of the default one.
Fixes: https://github.com/siderolabs/omni/issues/154
=> fix: make cluster machine install disk selector pick correct disk

internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
Add missing `Teardown` call in the `MachineSetNodeController`. Change the unit-tests to verify that removal with finalizers works.
=> fix: remove MachineSetNodes after links removal

client/pkg/omnictl/delete.go, hack/generate-certs/main.go
Start the watch before sending the destroy call to not miss events.
Add support for passing more than a single resource to the call, e.g., `omnictl delete link link-1 link-2 link-3`.
Additionally, bring back the "WatchKind" behavior when `--all` or `--selector` is used, or when the number of resources to be deleted is above a certain size.
=> fix: start watch before delete in `omnictl delete`

cmd/integration-test/pkg/tests/blocks.go, cmd/integration-test/pkg/tests/kubernetes.go, hack/generate-certs/main.go
Fix the flakiness in `ReplaceControlPlanes` test that was introduced by the recently added `KubernetesNodeAuditController`. This controller changed the Kubernetes node deletion logic to not block the `ClusterMachineTeardownController` for node deletions, as itself would take care of it later.
This causes the replaced control plane node in this test to be removed with a delay, as it is now removed by the audit controller after a grace period.
Improve the assertion between k8s<>Omni nodes by:
- not only asserting the number of nodes but also their names
- adding retries to this assertion, so it would keep trying until the audit controller does its job and removes the node from Kubernetes
- increasing its timeout to give the audit controller enough time (as it gives nodes a grace period of a …
=> test: fix flaky test by longer k8s node checks and retries

hack/test/freeze-a-vm.sh, hack/test/integration.sh, hack/test/restart-a-vm.sh, hack/test/wipe-a-vm.sh
Make half of the Talos nodes used in the integration tests to use a partial machine config to join Omni instead of kernel args. This would allow us to test more real use cases and catch more issues.
=> test: use Talos nodes with partial config in integration tests

internal/backend/runtime/omni/controllers/omni/schematic_configuration.go, internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
It should be no longer added to the `ExtensionsConfiguration` resource.
=> fix: drop outdated `SchematicConfigurationController` finalizer

go.mod, go.sum
This will allow upgrades to Kubernetes `v1.30.0`.
Fixes: #202
=> chore: bump `go-kubernetes` module

client/pkg/omni/resources/omni/machine_status.go, frontend/src/views/omni/Clusters/Management/ClusterCreate.vue, frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue, frontend/src/views/omni/Clusters/Management/ClusterScale.vue, internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/state_validation.go
Adding them to cluster will no longer work. Validation and the UI won't allow that.
We can not upgrade the node which doesn't have Talos installed yet. So the config generated for a different version of Talos will make this node never join the cluster. That's why we disable that.
Fixes: https://github.com/siderolabs/omni/issues/43
=> fix: do not allow adding ISO, PXE nodes running different Talos version

internal/backend/runtime/omni/controllers/omni/machine_set_node.go
Ignore such machine sets instead of failing, as fail leads to all other machine sets being skipped.
Fixes: https://github.com/siderolabs/omni/issues/208
=> fix: make `MachineSetNodeController` handle machinesets without clusters

frontend/src/views/omni/Auth/Authenticate.vue, internal/pkg/auth/auth0/token.go, internal/pkg/auth/interceptor/jwt.go
If the user has their email not verified, instead of failing with a generic error message of "invalid JWT", print an error message asking user to verify their email and try again.
In Auth0 mode, if the JWT validation has failed on the backend at the moment of clicking "Login", get a new ID token from Auth0 on the next click. This way, the user will not have to reload the page after validating their email - they can simply click "Login" again to get in.
Part of siderolabs/omni#114.
After this change is rolled out, we need to configure our Auth0 app to allow username/password auth.
**Demo:**
=> feat: improve auth flow when user email is not verified

cmd/omni/main.go, internal/pkg/config/config.go, internal/pkg/siderolink/manager.go
This lets the operator define url params for the api endpoint. For example https://<endpoint>/?grpc_tunnel=true. Instead of only appending the jointoken, we are parsing the url and adding it using Query.Set.
When configuring an ingress in front of omni, it is easier to use the grpc tunnel instead of opening an UDP port. But there is currently no way of setting grpc_tunnel to true by default. This change has a minimal effect on how the endpoint is handled while allowing an operator to set default param values.
=> feat: allow setting some url params for api endpoint

internal/backend/saml/saml.go, internal/backend/saml/session.go, internal/backend/saml/session_test.go
Fixes: https://github.com/siderolabs/omni/issues/230
=> fix: get all attribute values from SAML ACS when adding user labels

internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler_test.go
Fixes: https://github.com/siderolabs/omni/issues/244
There was an error in the logic that allowed updates of the machines even if the machine set has outdated machines already.
=> fix: properly do rolling update on control plane nodes

frontend/src/views/omni/MachineClasses/MachineClass.vue
Pretty common pitfall: `computed` doesn't work with `refs` which are not declared in the `setup` method of the component.
Fixes: https://github.com/siderolabs/omni/issues/249
=> fix: machine class edit page

Dockerfile, Makefile, internal/frontend/frontend.go
To avoid crosscompilation of the frontend tasks.
=> chore: always build frontend on BUILDPLATFORM

frontend/src/views/omni/ItemLabels/LabelsInput.vue
It was happening due to the wrong id was being used for the item key.
=> fix: get rid of duplicating label completion options

frontend/src/views/omni/Modals/UpdateExtensions.vue
The bug was leading to fetching `schematic-schematic-<machine-uuid>`, which is the incorrect name and it was always trying to create the resources instead of the update.
=> fix: use proper name for fetching existing extension configuration

frontend/src/components/common/Status/TStatus.vue, frontend/src/constants/index.ts, frontend/src/views/cluster/Nodes/NodeLogs.vue, frontend/src/views/cluster/Nodes/NodeOverview.vue, frontend/src/views/cluster/Nodes/NodeServiceEvents.vue, frontend/src/views/cluster/SideBarNode.vue, internal/backend/runtime/omni/controllers/omni/omni_test.go
Also pull the service list from the `MachineService.ServiceList` API as it has more data than the resource and has services which haven't started yet.
The list is dynamically updated by subscribing on the machine events and filtering the events of type `ServiceStateEvent`.
Additionally make the sidebar service list dynamically update for consistency.
Fixes: https://github.com/siderolabs/omni/issues/21
=> feat: show service events on the node overview page

internal/backend/grpc/auth.go, internal/pkg/auth/interceptor/jwt.go
Fix the grammar and improve the error messages about authentication.
=> fix: improve wording in authentication error messages

README.md
This fixes a broken link to the on-prem installation documentation
=> fix a typo in the on-prem installation link

cmd/integration-test/pkg/tests/auth.go, cmd/integration-test/pkg/tests/cli.go
To avoid any potential collisions based on timing.
Closes siderolabs/omni#303.
=> test: do not use epoch millis in service account names

internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go, internal/backend/runtime/omni/controllers/omni/machine_status_snapshot_test.go
Should be `ClusterMachine` not `ClusterMachineStatus`.
=> fix: read proper resource type in the `MachineStatusSnapshot`

internal/backend/runtime/omni/migration/helpers.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Looks like the test was broken in two places too and wasn't verifying anything:
- the status was missing the schematic and so the resources were just skipped by the `ClusterMachineConfig` controller.
- the `ClusterMachineTalosVersion` resources were ignored in the migration method and not created in the test.
So basically it was a bit outdated. Now it's in sync and I've checked that the test is failing with the buggy code.
=> fix: properly generate machine config input versions in the migration

frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Added `Cache-Control: no-store` header to all `HEAD` requests in `/image` path.
Close #324
=> feat: add Cache-Control header for head requests

frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Looks like setting headers as `Record<string, string>` doesn't work. Should use `new Headers()` instead.
=> fix: properly set `Cache-Control` header

frontend/src/router/index.ts, frontend/src/views/cluster/Config/PatchEdit.vue, frontend/src/views/cluster/Config/Patches.vue
When you open `cluster/machine/patches` it should go back to `cluster/machine/patches` after you finished editing. The bug was sending you to `machine/patches` out-of-cluster version of it.
=> fix: use proper routing on the config patch view and edit pages

internal/backend/grpc/router/omni_backend.go, internal/backend/grpc/router/resolve.go, internal/backend/grpc/router/talos_backend.go, internal/backend/grpc/router/talos_backend_test.go
We were not correctly checking if the nodes passed via `talosctl --nodes` were resolved before replacing the target in the GRPC metadata with the resolved ones.
We were handling a single node in the metadata correctly, but not doing the same handing for multiple nodes. This PR fixes that.
=> fix: pass through the `talosctl -n` args if they cannot be resolved

internal/backend/runtime/omni/controllers/omni/machine_status_snapshot_test.go
Fix the flaky test due to the race caused by the test ending before the last log, `task finished`, is written by the task runner.
=> test: fix a data race in `MachineStatusSnapshotController` unit tests

internal/backend/runtime/omni/controllers/omni/image_pull_status_test.go, internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
The code had an issue: if the loop pulled at least one image and one of the images in the end of the loop already exist on the node, it was skipping the update, so only the outdated event was sent to the channel.
=> fix: properly update the pulled images count if some images are skipped

client/api/omni/management/management.pb.gw.go, client/api/omni/oidc/oidc.pb.gw.go, client/api/omni/resources/resources.pb.gw.go, client/api/talos/machine/machine.pb.gw.go, go.mod, go.sum, internal/backend/grpc/grpc.go, internal/backend/grpc/router/router.go, internal/backend/server.go, internal/memconn/memconn.go
With new gRPC (both gateway and modules) it uses `grpc.NewClient` call to create clients. It no longer support custom addresses without a `passthrough:` prefix. Previous fix didn't account for that in some places, so this one changes the structure of `Transport` to always return address in proper form for external users.
=> fix: change Transport.Address field to Transport.Address method

internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
I have run it with `–count=100` and it no longer fails.
The https://github.com/golang/go/issues/67434 can't come soon enough, so we can drop all fake clocks.
=> fix: proper time adjustment to fix flaky TestEtcdManualBackup

internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
Otherwise the controller might get stuck trying to destroy the resource forever.
=> fix: ignore not found in the `MachineStatus` and `MachineStatusSnapshot`

client/go.mod, client/go.sum, go.mod, go.sum
Changes: https://github.com/cosi-project/runtime/pull/457
=> chore: bump COSI runtime to 0.4.5

internal/backend/grpc/oidc.go, internal/backend/oidc/external/external.go, internal/backend/oidc/internal/client/client.go
Looks like my assumption wasn't correct.
=> fix: properly detect `authcode-keyboard` oidc mode

frontend/src/notification.ts, frontend/src/views/omni/Modals/UserCreate.vue, internal/backend/runtime/omni/export_test.go, internal/backend/runtime/omni/omni.go, internal/backend/runtime/omni/state_validation.go, internal/backend/runtime/omni/state_validation_test.go
Validate the user email when creating a new identity.
Closes siderolabs/omni#312.
**Preview**
=> fix: validate user email on creation

internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
`migrateInstallImageConfigIntoGenOptions` was missing that check. Add the check and add the test.
=> fix: ignore not found `ClusterMachine` in the migrations

internal/backend/runtime/omni/controllers/omni/data/maintenance-config-patch.yaml, internal/backend/runtime/omni/controllers/omni/maintenance_config_patch.go, internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go, internal/backend/runtime/omni/omni.go
Accidentally hardcoded `8090` there :facepalm:
Fixes: https://github.com/siderolabs/omni/issues/310
=> fix: properly generate maintenance config patches

internal/backend/runtime/cosi/cosi.go
Should fix nil reference errors.
(cherry picked from commit https://github.com/siderolabs/omni/commit/6286340e38363aefadada987e9ac865fedab38d1)
=> fix: properly delete the item from the cached items slice

internal/backend/runtime/omni/controllers/helpers/helpers.go, internal/backend/runtime/omni/controllers/omni/internal/task/runner.go, internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go, internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go, internal/backend/runtime/omni/controllers/omni/machine_status_test.go, internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
The return type should be input type, not the output type. Also leverage runner equality functions to not to restart the collectors if nothing changed.
=> fix: use proper types in the machine status and snapshot controllers

internal/backend/runtime/omni/controllers/omni/installation_media.go
Add support for Akamai Connected Cloud (Linode) installation media in Omni.
=> chore: add Akamai installation media

internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go, internal/backend/runtime/omni/controllers/omni/machine_status.go
Fixes: https://github.com/siderolabs/omni/issues/378
That should fix the migration from the vanilla Talos images which do not exist in the image factory.
=> fix: generate schematics with the extensions, meta and kernel args

client/go.mod, client/go.sum, go.mod, go.sum, internal/backend/runtime/omni/controllers/omni/machine_set_node.go
This change fixes race during machine allocation in the machine class based machine sets, which was happening due to the eventual consistency of the in-memory cache.
=> fix: use un-cached list in the `MachineSetNodeController`

internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
Filter them in the same way as in manual allocation: available, connected and reporting events.
=> fix: make `MachineSetNode` controller select only connected machines

frontend/src/views/omni/Clusters/ClusterEtcdBackupCheckbox.vue
It was dropped, unfortunately linter didn't catch it.
=> fix: do not use `time` namespace to parseDuration

frontend/src/components/common/Tooltip/Tooltip.vue
Otherwise it might be hidden under the other elements.
=> fix: use proper index for the Tooltip

internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go, internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
Sort by the creation time of the `MachineSetNode` instead. As the creation time of the `ClusterMachineTalosVersion` doesn't replicate the creation time of the `MachineSetNode` anymore.
=> fix: do not use created time of the `ClusterMachineTalosVersion` in sort

frontend/src/components/common/Tooltip/Tooltip.vue
`9999` seems to break things. `auto` looks to be working properly.
=> fix: use proper `z-index` for the tooltip component

internal/backend/runtime/omni/controllers/omni/installation_media.go
It looks like it was missing there.
=> feat: add `Equinix metal` option in the download installation media

.gitignore, .kres.yaml, Makefile, go.work
This fixes `gopls` to look up usage correctly across sub-packages in the same repo.
=> chore: add `go.work` file

cmd/omni/main.go, internal/backend/runtime/omni/state_etcd.go, internal/pkg/config/config.go
Make them configurable, but provide sane defaults out of the box.
Part of #427
=> fix: enable etcd client keep-alives by default

internal/backend/grpc/management.go
This should fix `omnictl kubeconfig/talosconfig --break-glass` command.
=> fix: use proper permissions for cluster taint resource

internal/backend/runtime/omni/state_metrics.go
In addition to measuring operations, measure number of resources affected (important e.g. for list/watch operations, where a single operation might yield lots of resources).
<details>
```
> HELP omni_resource_throughput_total Number of resources processed by watches/reads/writes.
> TYPE omni_resource_throughput_total counter
omni_resource_throughput_total{kind="read",type="AuthConfigs.omni.sidero.dev"} 2
omni_resource_throughput_total{kind="read",type="BackupDatas.omni.sidero.dev"} 2
omni_resource_throughput_total{kind="read",type="ClusterBootstrapStatuses.omni.sidero.dev"} 3
omni_resource_throughput_total{kind="read",type="ClusterConfigVersions.omni.sidero.dev"} 10
omni_resource_throughput_total{kind="read",type="ClusterEndpoints.omni.sidero.dev"} 2 …
```
=> chore: add resource throughput metrics

internal/backend/grpc/router/router.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go, internal/pkg/siderolink/manager.go
And exclude port from the saved address.
Additionally fix Talos backends cache to not to
react on the `MachineType` `Create` and `Update` events.
=> fix: do not re-create peer on the remote addr change

go.mod, go.sum, internal/backend/grpc/router/router.go, internal/backend/grpc/router/server.go, internal/backend/grpc/router/talos_backend_test.go
Bump github.com/siderolabs/grpc-proxy to v0.4.1 and replace deprecated calls to `grpc.CustomCodec`.
Same as in https://github.com/siderolabs/talos/pull/8999
=> chore: bump deps

internal/backend/runtime/omni/migration/migrations.go
Otherwise we might miss the errors.
=> fix: add missing `return err` in the maintenance config drop migration

internal/backend/runtime/omni/controllers/helpers/helpers.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go, internal/backend/runtime/omni/controllers/omni/machine_set_status.go
Otherwise `ClusterMachineStatus` controller misses the machine set node removal and is not updating the stage to `BEFORE_DESTROY`.
=> fix: add finalizer on `MachineSetNode` resource in the controller

internal/backend/runtime/omni/controllers/omni/internal/machineset/workers_handler.go, internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
As we now have node audit and discovery service cleanup we don't have a strong requirement for LB to be healthy at the point of the node deletion.
This change will speed up nodes deletion and will not block the node deletion for the unhealthy clusters.
=> fix: do not expect LB to be healthy when scaling down workers

cmd/omni/main.go, internal/backend/grpc/configs_test.go, internal/backend/grpc/management.go, internal/backend/grpc/router/talos_backend.go, internal/backend/k8sproxy/k8sproxy.go, internal/backend/k8sproxy/middleware.go, internal/backend/k8sproxy/middleware_test.go, internal/backend/k8sproxy/multiplex.go, internal/backend/k8sproxy/proxy.go, internal/backend/runtime/omni/omni_test.go, internal/backend/runtime/omni/state_access.go, internal/backend/runtime/omni/virtual/state.go, internal/backend/workloadproxy/accessvalidator.go, internal/pkg/auth/accesspolicy/cluster.go, internal/pkg/auth/actor/actor.go, internal/pkg/auth/check.go, internal/pkg/auth/check_test.go, internal/pkg/auth/context.go, internal/pkg/auth/handler/auth_config.go, internal/pkg/auth/handler/handler_test.go, internal/pkg/auth/handler/signature.go, internal/pkg/auth/interceptor/auth_config.go, internal/pkg/auth/interceptor/jwt.go, internal/pkg/auth/interceptor/saml.go, internal/pkg/auth/interceptor/signature.go, internal/pkg/ctxstore/ctxstore.go, internal/pkg/ctxstore/ctxstore_test.go
Using so-called phantom types we can use the types themselves as keys directly without loosing performance. You no longer need to remember which type was attached to the thing you passed in context and can look up all fields access directly.
Part of #37
=> chore: rework auth.* keys, add `ctxstore` package

internal/backend/runtime/omni/controllers/omni/machine_set_status.go, internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
The condition was buggy: the controller wasn't removing finalizers from the `MachineSetNode`s if the machine set had 0 cluster machines.
=> fix: use proper check for the machine set teardown flow

cmd/integration-test/pkg/tests/kubernetes.go, internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
If the wrong version of the kubernetes components is used it won't bring down any pods as the upgrade will stop on the pre-pull phase.
=> fix: make image pre pull failure block the kubernetes update

frontend/src/views/omni/MachineClasses/MachineClass.vue
Fixes: https://github.com/siderolabs/omni/issues/466
Read the current labels from the watch.
=> fix: preserve labels on the `MachineClass` when editing it in the UI

internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
If the machineset had no machine class the controller was creating and removing `MachineSetRequiredMachines` in the loop due to bug in the code.
=> fix: do not recreate `MachineSetRequiredMachines` in the controller

frontend/src/views/omni/Machines/Machines.vue
If the number of registered machines is 0 just return 0 capacity.
=> fix: do not divide by 0 on the machine stats page

cmd/omni/main.go, go.mod, go.sum, hack/compose/docker-compose.yml, hack/generate-certs/main.go, internal/backend/grpc/auth.go, internal/backend/runtime/omni/audit/audit.go, internal/backend/runtime/omni/audit/gate.go, internal/backend/runtime/omni/audit/log.go, internal/backend/runtime/omni/audit/log_file_test.go, internal/backend/runtime/omni/audit/log_test.go, internal/backend/runtime/omni/audit/state.go, internal/backend/runtime/omni/audit/testdata/log/2012-01-01.jsonlog, internal/backend/runtime/omni/state.go, internal/backend/server.go, internal/pkg/auth/interceptor/jwt.go, internal/pkg/auth/interceptor/saml.go, internal/pkg/auth/interceptor/signature.go, internal/pkg/config/config.go, internal/pkg/grpcutil/audit.go, internal/pkg/grpcutil/logger.go, internal/pkg/grpcutil/stream_interceptors.go
This PR implements audit logs. To enable it you have to set the `--audit-log-dir` flag to a directory where the audit logs will be stored. The audit logs are stored in a JSON format.
Example:
```json
{"event_type":"update","resource_type":"PublicKeys.omni.sidero.dev","event_ts":1722537710182,"event_data":{"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36","ip_address":"<snip>","user_id":"a19a7a38-1793-4262-a9ef-97bc00c7a155","role":"Admin","email":"useremail@userdomain.com","confirmation_type":"auth0","fingerprint":"15acb974f769bdccd38a4b28f282b78736b80bc7","public_key_expiration":1722565909}}
```
Keep in mind that `event_ts` are in milliseconds instead of seconds. Field `event_data` contains all relevant …
=> feat: implement audit log

client/pkg/omni/resources/omni/labels.go, frontend/src/views/omni/ItemLabels/ItemLabels.vue, frontend/src/views/omni/Machines/MachineItem.vue, frontend/src/views/omni/Modals/MachineRemove.vue, internal/backend/runtime/omni/controllers/omni/machine.go, internal/backend/runtime/omni/controllers/omni/machine_request_link.go, internal/backend/runtime/omni/controllers/omni/machine_request_link_test.go, internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/backend/runtime/omni/omni.go
The controller handles all `MachineRequestStatuses` and adds labels to the links which IDs is specified in the `MachineRequestStatus` spec.
This flow should help to identify which links are managed by the machine requests.
=> chore: add request label to the links created by the cloud provider

internal/backend/workloadproxy/reconciler.go
Add the missed `nil` reference check to the workload proxy TCP load balancer upstreams reconciler.
=> fix: fix nil pointer dereference in workload proxy reconciler

internal/backend/runtime/omni/state_etcd.go
As Omni does lots of gRPC operations with etcd, it should help.
=> fix: add gRPC read buffer pool for etcd client

internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_status_test.go
`ClusterMachineStatus` controller should call `HandleInput` in the `FinalizerRemovalExtraOutputFunc` too.
=> fix: properly remove `MachineSetNode` finalizer in the controller

internal/backend/runtime/omni/controllers/omni/data/kube-service-exposer-config-patch.tmpl.yaml
Contains the fix for the goroutine leak on port conflict, see: https://github.com/siderolabs/kube-service-exposer/releases/tag/v0.2.0
Also, use the new `--disallowed-host-port-ranges` flag to prevent a set of known ports used by Talos to not be used by the exposer.
Closes #502.
=> feat: bump kube-service-exposer to v0.2.0

internal/pkg/siderolink/machines.go
We were not passing a logger to this, so its logs were going nowhere.
=> fix: pass the logger to machine logs circular buffer

.kres.yaml, LICENSE, hack/release.sh
Bring in https://github.com/siderolabs/kres/pull/436 from kres.
Closes siderolabs/omni#557.
=> chore: rekres to get BUSL license change date updated on releases

client/pkg/meta/meta.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go, internal/backend/runtime/omni/controllers/omni/omni_test.go
Remove the meta key to prevent auto-rollbacks, as Omni manages upgrades & downgrades.
Closes siderolabs/omni#509.
Depends on https://github.com/siderolabs/talemu/pull/17
=> fix: delete upgrade meta key from nodes after upgrades

internal/backend/extensions/extensions.go, internal/backend/extensions/extensions_test.go, internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go, internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
If an extension is renamed between minor Talos versions, rewrite its name to the newer one on upgrades and to older one on downgrades.
Handle the rename of `xe-guest-utilities` to `xen-guest-agent` happened on `1.6->1.7`, which was previously not handled correctly.
Additionally, closes siderolabs/omni#519.
=> chore: rewrite renamed extension names on Talos version updates

client/pkg/infra/controllers/provision.go, client/pkg/infra/infra_test.go, client/pkg/infra/provision/provision.go
The provider should know the config to use for the machine provisioning.
=> fix: add siderolink connection params to the infra provider interface

hack/release.toml, internal/pkg/siderolink/manager.go, internal/pkg/siderolink/siderolink_test.go
The code is already there: Talos will simply fail to connect and will try again by rotating the IP. We simply add support for specifing multiple IP's in the `siderolink-wireguard-advertised-addr` flag separated by a comma.
Fixes #495
=> chore: allow multiple IP's for `siderolink-wireguard-advertised-addr` flag

internal/backend/runtime/omni/controllers/omni/cluster_status.go
Fixes: https://github.com/siderolabs/omni/issues/609
=> fix: calculate requested and connected machines in the `ClusterStatus`

client/pkg/omnictl/get.go
The benefit is that if `omnictl` is out of sync with the server, it will still show correct server-side representation.
(If protobuf representation is out of sync with the server, it might skip unknown fields).
This doesn't affect other commands, like `apply` or `cluster template` family of functions, they still use protobuf representation.
=> fix: use YAML representation in `omnictl get`

cmd/integration-test/pkg/tests/infra.go, cmd/integration-test/pkg/tests/tests.go, cmd/integration-test/root.go, hack/test/integration.sh
Now Talemu based tests set up `MachineRequestSet` with 30 machines before the tests and tear it down after.
New blocks validate links and machine requests creation and deletion.
Fixes: https://github.com/siderolabs/omni/issues/366
=> test: run infra integration tests against Talemu provider

deploy/README.md, deploy/compose.yaml, deploy/env.template
Uses shell veriables so the template can be fed through envsubst to help people get started faster.
Will update docs at https://omni.siderolabs.com/how-to-guides/self_hosted/index once this template is available.
=> docs: update omni template so docs are easier

client/pkg/omnictl/download.go
It allows using commas as separator when specifying multiple values. Commas are probably not expected/intended in labels, and will never appear in extension names.
Leave `extraKernelArgs` as-is, as it can actually contain commas.
=> fix: parse machine labels and extensions as slices in `omnictl download`

client/pkg/infra/controllers/provision.go, internal/backend/runtime/omni/controllers/omni/machine_status.go
Otherwise the infra provider stops the machine before Omni can run the reset and everything gets stuck when the machine is allocated into a cluster.
Also fix labels not being reset on the machine status.
=> fix: call deprovision only after the machine request status is deleted

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, client/pkg/omni/resources/omni/machine_set.go, client/pkg/template/internal/models/machineset.go, client/pkg/template/operations/export.go, client/pkg/template/operations/testdata/export/cluster-resources.yaml, client/pkg/template/testdata/cluster-valid-bootstrapspec-resources.yaml, client/pkg/template/testdata/cluster1-resources.yaml, client/pkg/template/testdata/cluster2-resources.yaml, client/pkg/template/testdata/cluster3-resources.yaml, cmd/integration-test/pkg/tests/cluster.go, frontend/src/api/omni/specs/omni.pb.ts, frontend/src/api/resources.ts, frontend/src/components/common/Button/TButtonGroup.vue, frontend/src/methods/machineset.ts, frontend/src/states/cluster-management/index.ts, frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue, frontend/src/views/cluster/ClusterMachines/MachineSet.vue, frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue, frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue, frontend/test/unit/clusterManageState.spec.ts, internal/backend/runtime/omni/audit/data.go, internal/backend/runtime/omni/audit/hooks/hooks.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler_test.go, internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go, internal/backend/runtime/omni/state_validation.go, internal/backend/runtime/omni/state_validation_test.go
With that it becomes possible to get the machines from the machine request sets instead of the machine classes.
This opens the way for automated machine provisioning. Fixes: https://github.com/siderolabs/omni/issues/595
=> feat: support attaching machine sets to a machine request sets

cmd/omni/main.go, frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanelCondition.vue, frontend/src/views/omni/Modals/DownloadInstallationMedia.vue, frontend/src/views/omni/Overview/Overview.vue, hack/zstd-dict/data/machineconfig.tmpl.yaml
I'm a sucker for proper capitalization and noticed this in the hands-on lab under TalosCon.  This only changes the Omni web UI.  I've not touched the source itself as I did in https://github.com/siderolabs/talos/pull/8623.  I'm happy to do that too if you want.
I've added the `:` to show that it's a key example.  Just not to interfere with only having proper caps and the other not.  I can of course change this back. :smile:
=> chore: fix capitalization of wireguard

cmd/integration-test/pkg/tests/infra.go
The error message is misleading due to printing the wrong length.
=> test: fix the error message in infra test

client/pkg/cosi/labels/labels_test.go, client/pkg/cosi/labels/lexer.go
Improve the parser to support spaces in the values.
Fixes: https://github.com/siderolabs/omni/issues/647
=> fix: support whitespaces in the label selectors

frontend/src/methods/logs.ts
Otherwise it crashes the stream and it gets restarted.
=> fix: ignore parse errors in the log parser

client/api/omni/specs/siderolink.pb.go, client/api/omni/specs/siderolink.proto, internal/backend/logging/handler.go, internal/backend/server.go, internal/pkg/grpcutil/logger.go, internal/pkg/siderolink/manager.go
Currently, if gateway meets existing X-Forwarded-For header, it will append peer address that it sees to the existing value using comma. Our IP extraction function didn't account for that, and so it failed to parse IP and it used the original `peer.address` which set deep below in the gRPC middleware.
This commit ensures that we try to split the string value using `,`.
Closes #668
=> fix: get proper IP from peer metadata

client/pkg/omnictl/config/config.go
Checking for file-not-exist error is not enough.
Fixes #683
=> fix: properly return error from `config.Init`

deploy/helm/README.md, deploy/helm/omni/.helmignore, deploy/helm/omni/Chart.yaml, deploy/helm/omni/templates/_helpers.tpl, deploy/helm/omni/templates/deployment.yaml, deploy/helm/omni/templates/generic-device-plugin.yaml, deploy/helm/omni/templates/service.yaml, deploy/helm/omni/values.yaml
This PR adds a basic helm chart to deploy Omni in an existing Kubernetes cluster. It does not take care of gpg keys, certificates, etcetera, leaving that to the user's own devices.
=> add basic helm chart

internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go
Without this timeout the controller might hang forever.
=> fix: introduce timeout in the etcd healthchecks in the machine set ctrl

.github/workflows/ci.yaml, .kres.yaml, Dockerfile, Makefile, client/pkg/access/serviceaccount.go, client/pkg/access/validate.go, client/pkg/client/client.go, client/pkg/client/omni/omni.go, client/pkg/client/options.go, client/pkg/constants/constants.go, client/pkg/infra/controllers/provision.go, client/pkg/infra/infra.go, cmd/integration-test/pkg/clientconfig/clientconfig.go, cmd/integration-test/pkg/root.go, cmd/integration-test/pkg/tests/auth.go, cmd/integration-test/pkg/tests/blocks.go, cmd/integration-test/pkg/tests/cluster.go, cmd/integration-test/pkg/tests/tests.go, cmd/omni/cmd/cmd.go, internal/backend/grpc/serviceaccount.go, internal/backend/server.go, internal/pkg/auth/actor/actor.go, internal/pkg/auth/serviceaccount/serviceaccount.go, internal/pkg/config/config.go
Also:
- support generating the initial service account and dumping it's key somewhere.
- support running omni integration tests against the production build of Omni using a service account.
- enable `omni-integration-test` image.
=> feat: support insecure localhost infra provider access mode

.github/workflows/ci.yaml, .kres.yaml, Dockerfile, Makefile
=> fix: build arm64 integration tests executable

client/pkg/infra/controllers/provision.go, frontend/src/views/omni/MachineClasses/MachineClass.vue
The check was incorrect, so it was setting empty initial labels even if they are not set in the UI.
=> fix: do not set empty initial labels in the UI

internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
It makes little sense to show them in Omni.
Fixes: https://github.com/siderolabs/omni/issues/655
=> fix: filter block devices with UNKNOWN type

internal/backend/runtime/omni/controllers/omni/versions.go
It was reading from the image registry if the pre-release versions are enabled, but that doesn't work as factory won't generate the images for versions which are not in the list.
=> fix: do not read Talos versions from the image registry ever

frontend/src/views/omni/MachineClasses/MachineClass.vue
We added `no-manual-allocation` filter there, but it was added using `OR`. It should be concatenated with each condition in `OR` to work as `AND`.
=> fix: use proper selectors in the MachineClass create UI

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
It looks like they weren't removed for Talos < 1.5.0, due to absence of the maintenance config patches for these machines.
=> fix: remove `MaintenanceConfigPatchController` finalizers

.golangci.yml, cmd/integration-test/pkg/tests/talos.go, internal/backend/dns/service.go, internal/backend/dns/service_test.go, internal/backend/grpc/router/resolve.go, internal/backend/grpc/router/router.go
`talosctl --cluster` flag is now optional, Omni will automatically resolve the cluster if the machine is a part of one.
Fixes: https://github.com/siderolabs/omni/issues/620
=> feat: automatically resolve cluster in `talosctl` calls

.github/workflows/ci.yaml, .github/workflows/e2e-backups-cron.yaml, .github/workflows/e2e-forced-removal-cron.yaml, .github/workflows/e2e-scaling-cron.yaml, .github/workflows/e2e-short-cron.yaml, .github/workflows/e2e-short-secureboot-cron.yaml, .github/workflows/e2e-upgrades-cron.yaml, .github/workflows/e2e-workload-proxy-cron.yaml, .github/workflows/slack-notify.yaml, .golangci.yml, .kres.yaml, cmd/integration-test/pkg/root.go, cmd/integration-test/pkg/tests/infra.go, cmd/integration-test/pkg/tests/talos.go, cmd/integration-test/pkg/tests/tests.go, hack/test/integration.sh, hack/test/provisionconfig.yaml, internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go, internal/backend/runtime/omni/controllers/omni/machine_set_status.go, internal/backend/runtime/omni/pkg/check/etcd.go
Talos running in secure boot is very unstable in QEMU, it's the main source of test flakiness.
So secureboot tests will run on cron and in Talemu only.
Split e2e-scaling tests: extract forced removal flows from it. Changed the tests flags to support more complicated machine provision flows: now it can read the config from the yaml file.
=> test: disable secure boot in e2e tests

internal/backend/runtime/omni/controllers/omni/machine_teardown.go, internal/backend/runtime/omni/omni.go, internal/pkg/siderolink/manager.go
The reset removes Talos from the machine completely. Fixes: https://github.com/siderolabs/omni/issues/419
=> feat: reset machine when it's removed from Omni

client/pkg/infra/controllers/provision.go, client/pkg/infra/infra_test.go, client/pkg/infra/provision/context.go, client/pkg/omni/resources/infra/config_patch_request.go, client/pkg/omni/resources/infra/infra.go, cmd/integration-test/pkg/tests/auth.go, cmd/integration-test/pkg/tests/stats.go, internal/backend/runtime/omni/controllers/omni/infra_provider_config_patch.go, internal/backend/runtime/omni/controllers/omni/infra_provider_config_patch_test.go, internal/backend/runtime/omni/infraprovider/state_test.go, internal/backend/runtime/omni/omni.go
Patches can be created for a single machine in the machine provision flow: the provider can call `CreateConfigPatch` method at any point. This will create a `ConfigPatchRequest` resource which will be turned into a `ConfigPatch` after the `MachineRequestStatus` UUID gets populated.
Fixes: https://github.com/siderolabs/omni/issues/728
=> feat: support creating config patches in the infrastructure providers

cmd/integration-test/pkg/root.go, cmd/integration-test/pkg/tests/tests.go
The change which introduced multiple infra provider configs support in the tests has broken the case when there's auto provisioning without pre-allocated machines.
=> fix: properly set up provider for autoprovision tests

internal/pkg/constants/versions.go
Now the minimum supported version of Talos is 1.5 (as per our support policy).
Running existing clusters on 1.4 will be still possible.
=> chore: deprecate Talos 1.4

.github/workflows/slack-notify.yaml, go.mod, go.sum
See: https://github.com/siderolabs/discovery-service/releases/tag/v1.0.8
=> chore: bump discovery service to `v1.0.8`

cmd/integration-test/pkg/tests/cluster.go, cmd/integration-test/pkg/tests/extensions.go, cmd/integration-test/pkg/tests/infra.go, cmd/integration-test/pkg/tests/tests.go
Add an integration test, which is supposed to be run by a static infra provider, to test the cluster creation/destruction/re-creation flow.
Used in https://github.com/siderolabs/omni-infra-provider-bare-metal/pull/1.
Related to #660.
=> test: add static infra provider (bare-metal provider) integration tests

internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Otherwise it breaks config update for the Talos version which do not support `MetaDelete` API.
=> fix: ignore `Unimplemented` errors in `MetaDelete` calls

client/go.mod, client/go.sum, go.mod, go.sum
Include the fix in https://github.com/cosi-project/runtime/pull/528.
=> chore: bump COSI runtime to `v0.7.5`

internal/backend/runtime/omni/controllers/omni/infra_machine.go
We were generating a random wipe id multiple times in infra.MachineController, causing the infra provider to run many reconciles.
Fix it by doing it only once by checking the allocation information.
=> fix: regenerate wipe id of infra machines only once per de-allocation

client/go.mod, client/go.sum, go.mod, go.sum
This means full compatibility with future 1.9.0.
The schemas were updated in bbbf6f2c770914a6c5c98ecec39113dfa832d122.
=> feat: update Talos machinery to final 1.9.0-beta.1

cmd/integration-test/pkg/tests/infra.go
Assert that a set of known labels are set by the static infra provider on the `InfraMachineStatus` resources.
=> test: assert machine labels in static infra provider tests

internal/backend/saml/session.go
Add mappings for SAML attributes provided by default in [Zitadel](https://zitadel.com/docs/). This allows signing in with self-hosted Zitadel IdP. Without this PR Omni fails to identify the user name in the SAML response and the user gets an error message after signing in and the web console is inaccessible.
More info: https://zitadel.com/docs/guides/integrate/login/saml#saml-requests-and-responses
As a workaround, it is possible to get Zitadel to provide extra attributes that match the names of the fields that Omni expects by using a custom Zitadel Action on the Complement SAMLResponse/Pre SAMLResponse creation trigger, although it takes a little bit of manual extra effort from the Zitadel admin to add this.
For reference, this is the workaround script I have used on my self-hosted …
=> feat: Add support for Zitadel IdP

internal/backend/runtime/omni/state_validation.go, internal/backend/runtime/omni/state_validation_test.go
Accepting a previously rejected machine is ok, unlike rejecting a previously accepted machine.
Also prevent going back to the pending status from the accepted or rejected statuses.
=> fix: allow accepting rejected infra machines

internal/backend/runtime/omni/validated/state.go, internal/backend/runtime/omni/validated/state_test.go
If some operation violates destroy validations, we probably want it to not switch to TearingDown phase either. So we now run destroy validations as well as update validations when a resource is attempted to be torn down.
=> fix: run destroy validations on teardown

internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go, internal/backend/runtime/omni/controllers/omni/machine_status_test.go
If Talos is in agent mode, we should avoid preserving the list of extensions for the actual Talos installation, as the `metal-agent` extension breaks the Talos installation.
Related to/workaround for https://github.com/siderolabs/omni/issues/797
=> fix: do not preserve extensions on Talos agent mode

internal/backend/runtime/omni/export_test.go, internal/backend/runtime/omni/state_etcd.go, internal/backend/runtime/omni/state_etcd_election.go, internal/backend/runtime/omni/state_etcd_election_test.go
Abort Omni correctly if the lease is lost.
Add a unit-test simulating this.
=> fix: etcd lease handlining

frontend/src/router/index.ts
It was broken due to the incorrect object merge.
=> fix: display nodes sidebar

client/go.mod, client/go.sum, client/pkg/omnictl/delete.go, client/pkg/omnictl/output/table.go, client/pkg/template/operations/status.go, client/pkg/template/operations/sync.go, go.mod, go.sum, internal/backend/dns/service.go, internal/backend/grpc/router/router.go, internal/backend/runtime/cosi/cosi.go, internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go, internal/backend/runtime/omni/controllers/omni/internal/task/snapshot/snapshot.go, internal/backend/runtime/omni/controllers/omni/machine_request_set_status_test.go, internal/pkg/siderolink/loghandler.go
This brings in watch restarts for controller-runtime.
=> fix: bring in new versions of COSI runtime and state-etcd

frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
If the hostname label is missing from the ClusterMachineStatus, we fall back to the machine ID as the displayed name in the UI. Fix the check in this fallback logic.
=> fix: fallback to machine ID correctly if its hostname is missing

client/pkg/omni/resources/omni/labels.go, cmd/integration-test/pkg/tests/infra.go, internal/backend/runtime/omni/controllers/omni/machine_status.go
Copy the labels set on infra.MachineStatus to omni.MachineStatus resources.
Introduce a special prefix for the labels set by infra providers, so that they can keep track and synchronize the labels as needed.
Related to/depends on https://github.com/siderolabs/omni-infra-provider-bare-metal/pull/16.
=> feat: sync infra machine labels onto the machine status

internal/backend/runtime/omni/controllers/omni/infra_machine.go, internal/backend/runtime/omni/controllers/omni/infra_machine_test.go, internal/backend/runtime/omni/controllers/omni/machine_cleanup.go
There were cases when an infra machine was accepted, it was powered off by the infra provider too quickly, before its specs were populated by the `MachineStatus` poller. This caused additional issues as some other resources like `SchematicConfiguration` were also never created, blocking cluster creation.
Address this by setting the preferred power state of the infra machine to ON until its status is populated (we check this by checking the secure boot status field).
Additionally, clean up `InfraMachineConfig` resources (user-managed) when a machine is deleted.
Closes #798.
=> fix: wait for infra machine info to be collected before powering off

internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
Need to treat `nil` hostname as no hostname and wipe the current value in the `MachineStatus`.
=> fix: properly reset `MachineStatus` hostname for deallocated machines

frontend/src/views/omni/Modals/MachineAccept.vue
Warn the user that its disks are going to be wiped.
Per @steverfrancis's feedback.
=> feat: add disk wipe warning when accepting a pending machine

internal/pkg/machineevent/handler.go
Fix the error handling in the "create or update" logic on the `MachineState` resources in the machine sequence event handler.
=> fix: correctly handle conflict error in machine status handler

cmd/integration-test/pkg/root.go, cmd/integration-test/pkg/tests/infra.go, cmd/integration-test/pkg/tests/tests.go
Change the integration tests structure to enable running
any tests against the static infra providers: extract machine
acceptance/cleanup code into the pre/post hooks.
Introduce the flags to disable pre-installed extensions checks.
=> test: extract static infra provider machine accept tests into hooks

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Abusing generics to compress uncompressed data in `*omni.ConfigPatch`, `*omni.ClusterMachineConfig`, `*omni.RedactedClusterMachineConfig` and `*omni.ClusterMachineConfigPatches`.
Fixes #853
=> chore: migrate uncompressed resources data

internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Prevent migration errors. Also update tests.
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
=> fix: do not compress resources with phase != running (backport)

internal/backend/dns/service.go, internal/backend/dns/service_test.go
There was a problem with the node resolution (a.k.a. DNS) cache of the nodes. When a machine is in maintenance mode, there is a corresponding `MachineStatus` resource for it, but there isn't any `ClusterMachineIdentity`. Both of these types trigger updates in the node resolution cache. When a machine was never part of a cluster, the only source is `MachineStatus`, and the cache updates on it did not populate the machine ID in the cache. This caused the GRPC router to pick the wrong destination.
Furthermore, we did not remove the cluster and node name information from the cache when a machine was removed from a cluster. This caused the cache to contain obsolete cluster information, causing Talos GRPC proxy to not proxy the requests correctly after a machine was removed from a cluster. …
=> fix: fix node resolution cache for nodes in maintenance mode

client/pkg/omnictl/internal/access/client.go, cmd/omni/cmd/cmd.go, internal/backend/grpc/grpc_test.go, internal/backend/runtime/omni/controllers/omni/cluster_bootstrap_status.go, internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go, internal/backend/runtime/omni/controllers/omni/machine_teardown.go
- `NewClusterBootstrapStatusController.TransformExtraOutputFunc` gets `*client.Client` but forgets to close it.
This leads to `*grpc.ClientConn` leakage.
- `MachineTeardownController.resetMachine` gets `*client.Client` but forgets to close it.
This leads to `*grpc.ClientConn` leakage.
- `runWithState` gets `*discovery.Client` but forgets to close it. This leads to `*grpc.ClientConn` leakage.
- `WithClient` gets `*client.Client` but forgets to close it. This leads to `*grpc.ClientConn` leakage.
Shorten the code in some places, while we are at it.
=> fix: close grpc connections after their usage is complete

internal/backend/saml/saml.go
Should probably help with logging into the system initiated from the SAML apps Google drawer.
=> fix: enable IDP initiated SAML logins

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go, internal/pkg/config/config.go
Turns our we never enabled this compression before in omni. We DID enable it for integration tests, omnictl and omni client. Just not for the omni itself.
=> chore: omni enable config compression by default

internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
Do not ignore disks of the UNKNOWN type if their modalias is not empty and subsystem is `/sys/class/block`.
This is the workaround for Talos not detecting the correct disk types for some environments.
=> fix: detect more block devices

client/pkg/omnictl/talosconfig.go
I told Tim Jones in the ursamajor chat that I couldn't figure out how to use talosctl with maintenance mode machines that were connected to Omni. He told me to download the talosconfig on the main Omni page, not the ones on the cluster pages. I had been downloading my talosconfigs via omnictl so I didn't even realize this was an option.
=> docs: how to download generic talosconfig in omnictl talosconfig help

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migrations.go
Rename it from `compressMachineConfigsAndPatches` `compressConfigsAndMachinePatches` just to make sure.
=> chore: add `compressConfigsAndMachinePatches` migration back

cmd/omni/cmd/cmd.go, internal/pkg/config/config.go, internal/pkg/siderolink/manager.go, internal/pkg/siderolink/provision.go, internal/pkg/siderolink/provision_test.go
With the feature flag it is now possible to use the old flow.
The new secure join flow is not stable yet, so the default mode is legacy, which doesn't enable node unique token generation for all machines, not only the ones using too old Talos versions.
=> feat: add a flag to enable secure join token flow

client/go.mod, client/go.sum, cmd/integration-test/pkg/tests/talos.go, cmd/integration-test/pkg/tests/template.go, go.mod, go.sum
Use dedicated request timeout in the function to clear connection refused. Otherwise the request might hang forever and will fail the whole retry block.
Increase templates cluster health check timeout. Kubernetes components sometimes flap to unhealthy for a short moment after the cluster is healty.
=> tests: improve e2e upgrades and e2e templates tests stability

internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Update the resources ignoring ownership checks.
Also fix the unit tests, they had 2 issues:
1. It was disabled and had the wrong migration name in the filter.
2. Migration wasn't creating the resources with owners.
=> fix: fix config compression migration

frontend/src/views/omni/Machines/Machines.vue, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
The old logic could ignore version check if the install image Talos version isn't populated.
There's another check inside the version sync function that skips reconciliation if the install image isn't populated: it should catch it.
Also fix the typo in the UI.
=> fix: fix bug with Omni adding machine to a cluster before upgrading

internal/pkg/siderolink/manager.go
It seems SideroLink logs are too verbose in debug mode when the GRPC tunnel is used. Reduce their level to info.
Closes https://github.com/siderolabs/omni/issues/958.
=> fix: increase log level of the SideroLink GRPC tunnel handler

frontend/src/views/omni/Extensions/ExtensionsPicker.vue
I got the omni fe dev env working and decided to submit a small bug fix as a reward to myself :)
Fix extensions scroll list being hidden on horizontally tight screens by adding a small minimal height that allows to see about two rows.
fixes https://github.com/siderolabs/omni/issues/889
https://github.com/user-attachments/assets/b939437e-d06c-4fd7-a014-85430971f136
=> fix: extentions list hidden on small screens

frontend/src/components/common/MenuItem/TMenuItem.vue
Changes introduced in c662c2e0305dddd0cafe56a782a88b887bc59001 broke the regular links from opening in a new tab, as the click handler was preventing default behavior for all links. This fix ensures that regularLink entries are not affected while maintaining proper behavior for expandable menu items.
=> fix: fix exposed service links on the sidebar

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Migration takes a lot of time before booting Omni. The PR that only migrates `ConfigPatch` and no other resources will be the next one in chain.
For #966
=> fix: disable `compressConfigsAndMachinePatches`

internal/backend/runtime/omni/controllers/omni/maintenance_config_status.go, internal/backend/runtime/omni/controllers/omni/maintenance_config_status_test.go
If a machine does not support multidoc (<1.5.0) or running un agent mode, do not fail the maintenance apply controller - skip applying without failure instead.
Closes https://github.com/siderolabs/omni/issues/973.
=> fix: skip applying maintenance config to unsupported machines

internal/backend/runtime/omni/controllers/omni/config_patch_metrics.go, internal/backend/runtime/omni/omni.go
Add metric which describes the sizes of `uncompressed` and `compressed` config patches.
=> chore: add `omni_machine_config_patch_size` metrics

go.mod, internal/backend/extensions/extensions.go, internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go, internal/backend/runtime/omni/controllers/omni/talos_extensions.go, internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
It is a special extension and users should not be confused by it.
=> fix: exclude `metal-agent` extension from available extensions

client/api/omni/specs/cluster_machine_config.go, client/api/omni/specs/cluster_machine_config_patches.go, client/api/omni/specs/compression.go, client/api/omni/specs/config_patch.go, client/api/omni/specs/redacted_cluster_machine_config.go, client/pkg/compression/compression.go, client/pkg/compression/compression_test.go, client/pkg/constants/constants.go, internal/backend/runtime/omni/controllers/omni/infra_provider_config_patch_test.go, internal/backend/runtime/omni/controllers/omni/internal/machineset/operations.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
Change `SetUncompressedData` methods to respect `compressionThresholdBytes` from
`internal/backend/runtime/omni/state_etcd.go` while we are at it.
Fix len(data) == 0 != nil bug.
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
Co-authored-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
=> chore: migrate ConfigPatches above threshold of 2048

client/pkg/omni/resources/omni/etcd_backup_overall_status.go, client/pkg/omni/resources/omni/etcd_backup_status.go, frontend/src/methods/index.ts, frontend/src/views/cluster/Backups/BackupsList.vue, frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanel.vue, frontend/src/views/omni/Settings/BackupStorage.vue, internal/backend/runtime/omni/external/state_test.go, internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
The resources `EtcdBackupStatus` and `EtcdBackupOverallStatus` get updated very frequently, as both succeeded and failed attempts of backups trigger an update. Some users have a lot of clusters with many of them are inaccessible/dead, causing excessive resource updates.
Move these two resource types into the `metrics` namespace - the namespace for the frequently updated resources.
Noticed while investigating frequently updated resources while working on https://github.com/siderolabs/omni/issues/789.
=> perf: move etcd backup status resources into secondary storage

frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue, frontend/src/views/cluster/ClusterMachines/ClusterMachinePhase.vue, frontend/src/views/cluster/ClusterMachines/MachineSetPhase.vue, internal/e2e-tests/main_test.go
The way it was implemented there was incorrect.
Drop direct `popper` usage there and use the Tooltip instead.
Fixes: https://github.com/siderolabs/omni/issues/1004
=> fix: do not clip the tooltip in the cluster machine status

client/pkg/omni/resources/siderolink/connection_params.go, cmd/omni/cmd/cmd.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go, internal/pkg/siderolink/manager.go, internal/pkg/siderolink/provision.go, internal/pkg/siderolink/provision_test.go
Followup fix after https://github.com/siderolabs/omni/pull/976.
Change the way the global flag `--siderolink-use-grpc-tunnel` works: It now is used in the SideroLink provision API to decide whether to ignore what the machine requests in the prevision request and "force" the tunnel mode.
Additionally, now it is ignored in the generated `SideroLinkConfig` document which is pushed to the machines when they are allocated - instead, we simply check if the machine was already connected (provisioned) using a GRPC tunnel, and preserve that option. By doing that, we avoid switching the mode after the provisioning, avoiding the bug which is fixed in https://github.com/siderolabs/talos/pull/10517.
=> fix: do not switch Siderolink GRPC tunnel mode after provisioning

.vscode/settings.json
A small followup to [#998](https://github.com/siderolabs/omni/pull/998)
Without this option set the language server complains about synctest package not existing and in-editor compilation and test features stop working.
=> chore: add GOEXPERIMENT env to vscode config

client/pkg/cosi/labels/labels_test.go, client/pkg/cosi/labels/lexer.go, frontend/src/methods/labels.ts, frontend/src/views/omni/MachineClasses/MachineClass.vue
If a label value contains a comma, quote the label value when building the label selector. Change the label selector parser to read quoted strings as a single value, do not split them by commas.
Closes https://github.com/siderolabs/omni/issues/1018.
=> fix: correctly parse commas in label selectors

frontend/src/views/omni/Machines/Machines.vue
`s/Capacity/Capacity Free`.
Fixes: https://github.com/siderolabs/omni/issues/864
=> fix: use clearer description on the machines page metrics

internal/backend/runtime/omni/controllers/omni/config_patch_cleanup_test.go, internal/backend/runtime/omni/controllers/omni/etcd_backup.go, internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go, internal/backend/runtime/omni/controllers/omni/omni_test.go
The change from `context.WithTimeout` was unintentional, so lets revert that.
=> fix: restore timeout in `OmniSuite.SetupTest`

cmd/omni/cmd/cmd.go, hack/release.toml, internal/backend/runtime/omni/controllers/omni/cluster_bootstrap_status_test.go, internal/backend/runtime/omni/controllers/omni/etcd_backup_mock_2_test.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/disabledstore.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/filestore.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/metrics.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/store.go, internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store.go, internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store_test.go, internal/backend/runtime/omni/controllers/omni/secrets_test.go, internal/backend/runtime/omni/omni.go, internal/backend/runtime/omni/state_validation_test.go, internal/pkg/config/config.go
This is easier to process for the cli operator, since we now force it being at least 1 Mbps.
It also fixes the problem of limiter incorrectly assuming that the reader will use the entirety of a passed buffer,
resulting in incorrect limiting.
=> chore: change upload and download limits flags to mbps

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
For the needed machines, create a config patch with a low priority to preserve the config changes which require the machines to be rebooted.
Prevents the reboot due to the fix in https://github.com/siderolabs/omni/issues/1097.
Part of the fix for https://github.com/siderolabs/omni/issues/1095.
=> fix: create config patches to prevent reboot on version contract revert

internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
The db version is at len(migrations) after migrations are completed. So if we ran migration 39, it would be at 40.
Change the condition to properly handle that.
=> fix: properly skip the contract config patch removal migration

internal/backend/grpc/support.go, internal/backend/workloadproxy/handler.go
- Include exposed services in the support bundles.
- Produce a log when an exposed service request is redirected to the login (do not log other requests to avoid excessive logging).
Closes #1068.
=> feat: improve logging/debugging of exposed services

internal/pkg/siderolink/provision.go
If the `Link` already exists and is being torn down, we were returing pretty cryptic error back.
Replace the error message with the one which better describes what the user should do to fix the issue with the node not being able to join.
=> fix: return proper errors for the SideroLink provision API

internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
This pre-dates OIDC-based Kubernetes API access when we used the "plain" kubeconfigs (same as `talosctl kubeconfig`) but replaced the server address with Omni's. It is not necessary anymore with the current way of Omni proxying kube-apiserver calls.
=> fix: do not add omni api host to kube-apiserver cert SANs

internal/backend/oidc/internal/storage/keys/storage_test.go
The test was flaky due to it being time-sensitive - at the end of the test, it could have generated 2 or more keys, which we expected in the first assertion, but in the second one we compared it to a fixed set of keys of size 2.
=> test: fix the flaky key storage test

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, client/pkg/omni/resources/omni/cluster_machine_identity.go, client/pkg/omni/resources/omni/discovery_affiliate_delete_task.go, client/pkg/omni/resources/omni/omni.go, cmd/integration-test/pkg/tests/auth.go, cmd/omni/cmd/cmd.go, frontend/src/api/omni/specs/omni.pb.ts, frontend/src/api/resources.ts, internal/backend/discovery/clientcache.go, internal/backend/discovery/internal/discovery/client.go, internal/backend/grpc/configs_test.go, internal/backend/grpc/grpc_test.go, internal/backend/grpc/support.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_identity.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go, internal/backend/runtime/omni/controllers/omni/discovery_affiliate_delete_task.go, internal/backend/runtime/omni/controllers/omni/discovery_affiliate_delete_task_test.go, internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go, internal/backend/runtime/omni/omni.go, internal/backend/runtime/omni/omni_test.go, internal/backend/runtime/omni/state_access.go, internal/backend/runtime/omni/talosconfig_test.go
Rework the discovery service affiliate deletion by doing the following changes:
1. Add support for arbitrary discovery services (e.g., self-hosted or third party):
- Read the discovery service used by a machine from the machine itself
- Implement a cache for discovery service clients
- Use this discovery service client to remove the affiliate on node removal.
2. Make the discovery affiliate deletion asynchronous:
- Introduce `DiscoveryAffiliateDeleteTask` resource
- When a node is removed from a cluster, a resource for this node ID is created
- A controller continuously tries to remove the affiliate until it succeeds or until it gets expired in the discovery service itself (after 30 minutes)
- The controller removes the `DiscoveryAffiliateDeleteTask` resource
Closes #1084, closes #1085.
=> feat: implement async delete from discovery service(s)

frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
The same fix we did for download installation media screen - alphabetic sorting does not order the versions as we expect anymore starting with Talos 1.10.
=> fix: sort Talos versions by semver on the cluster creation screen

internal/backend/runtime/omni/controllers/omni/versions.go, internal/pkg/constants/versions.go
Kernel args were constant in Talos before UKI support, so Omni drops them by default when generating/rebuilding schematics. So if the Machines are upgraded to 1.10 and switch to UKI, they will be disconnected from Omni.
Do not allow using Talos 1.10, until we introduce proper support for the UKI non-secureboot machines.
=> fix: disable Talos >= 1.10 for now as Omni isn't ready for it yet

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, client/pkg/template/internal/models/machineset.go, client/pkg/template/operations/export.go, client/pkg/template/operations/testdata/export/cluster-resources.yaml, client/pkg/template/testdata/cluster3-resources.yaml, frontend/src/api/omni/specs/omni.pb.ts, frontend/src/states/cluster-management/index.ts, frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue, frontend/test/unit/clusterManageState.spec.ts, internal/backend/runtime/omni/controllers/omni/machine_provision.go, internal/backend/runtime/omni/controllers/omni/machine_set_node.go, internal/backend/runtime/omni/state_validation.go, internal/backend/runtime/omni/state_validation_test.go
This option is redundant. It was inteded for MCP, but the MCP implementation will not be using it, so we should stop dragging it along anymore.
This change was extracted from https://github.com/siderolabs/omni/pull/723
=> fix: remove machine set allocation source option

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, frontend/src/api/omni/specs/omni.pb.ts, frontend/src/views/cluster/Nodes/NodeOverview.vue, frontend/src/views/omni/Machines/MachineItem.vue, internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go, internal/backend/runtime/omni/controllers/omni/infra_machine.go, internal/backend/runtime/omni/controllers/omni/infra_machine_test.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go, internal/backend/runtime/omni/controllers/omni/machine_config_gen_options.go, internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/backend/runtime/omni/controllers/omni/omni_test.go, internal/backend/runtime/omni/controllers/omni/schematic_configuration.go, internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go, internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go, internal/backend/runtime/omni/migration/migration_test.go
With Talos v1.10, even non-secure boot machines can be booted with a UKI. Replace the secure boot status collection and handling logic to take UKI boot into consideration instead.
This affects which schematic ID we use to compare the desired vs actual schematics.
Closes https://github.com/siderolabs/omni/issues/1070.
=> fix: collect and handle UKI boot information

internal/backend/runtime/omni/controllers/omni/machine_config_gen_options.go, internal/backend/runtime/omni/controllers/omni/machine_config_gen_options_test.go
It was inverted, so it was picking the biggest disk.
=> fix: use the correct sort order for the automatic install disk selection

.golangci.yml, client/.golangci.yml, frontend/src/views/omni/Auth/Authenticate.vue
We had a URL encoding issue in the `redirect` query parameter in the new workload proxy auth/redirect flow. On the authentication page, we URL-decoded the redirect URL to be used after the authentication, but forgot to re-encode it before issuing the redirect afterwards, which submits it to the backend.
Backend then was unable to base64-decode the signed redirect URL, resulting in a bad request.
Closes #1168.
=> fix: correctly encode exposed service redirect URL after auth

frontend/src/views/cluster/ExposedService/ExposedServiceSideBar.vue
If the exposed services have any issues, the UI was crashing and not rendering anything.
Show the proper warning instead.
=> fix: gracefully render exposed services errors

cmd/integration-test/pkg/tests/talos.go, hack/test/integration.sh
The internal timeout for the provision test is 6 minutes. With 4 minutes timeout for the whole test run we miss the actual error report.
=> test: bump Talemu tests timeout

frontend/src/components/common/Form/JsonForm.vue, frontend/src/states/cluster-management/index.ts, frontend/test/unit/clusterManageState.spec.ts, frontend/test/unit/watch.spec.ts
The way resources were ordered was making config patch being created before machine set node resources.
That kind of order makes Omni code racy and it might install Talos to the wrong disk for example.
=> fix: use the correct res order for the cluster operations in the UI

internal/backend/saml/saml.go
It looks like the library update requires a new argument which we didn't pass.
Fixes: https://github.com/siderolabs/omni/issues/1188
(cherry picked from commit aa24c7c707506d8bc2919482b140ebf43776631e)
=> fix: fix crash in the SAML ACS handler

internal/backend/runtime/omni/controllers/omni/cluster.go, internal/backend/runtime/omni/controllers/omni/cluster_uuid.go
Keeping `ClusterUUID` also keeps `EtcdBackupEncryptionController` alive. Which can help in case of accental cluster teardown call, if the cluster is stuck in destroying phase.
=> fix: keep ClusterUUID resource alive until the cluster is destroyed

internal/backend/runtime/omni/migration/manager.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
There was `MachineClassStatusController` that wasn't used for long. It was introduced and dropped within one minor Omni version. But if that particular Omni version was used, the controller would add it's finalizer on the `MachineClass` resources.
Then as the controller is dropped, nothing removes the finalizer.
Introduce migration to drop that finalizer forcefully.
Fixes: https://github.com/siderolabs/omni/issues/1197
=> fix: remove deprecated controller finalizers from the machine classes

go.mod, go.sum
This includes multiple fixes:
* https://github.com/siderolabs/go-kubernetes/pull/30
* https://github.com/siderolabs/go-kubernetes/pull/31
=> fix: update go-kubernetes library to the latest version

frontend/test/unit/methods/cluster.spec.ts
Addresses #1131
Some updates in this PR
- Added a  Return Type `Promise<string>`  to the nextAvailableClusterName function.
- Unit test to cover some edge cases for the function.
=> test: add unit test for nextAvailableClusterName function

go.mod, go.sum, internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go
As the latest AWS lib version breaks a bunch of S3 compatible storage providers, because of inability to disable integrity checks for multipart uploads.
See: https://github.com/aws/aws-sdk-go-v2/issues/3007
Fixes: https://github.com/siderolabs/omni/issues/1206
=> fix: pin AWS s3 libs version to 1.72.3

frontend/src/methods/auth.ts, frontend/src/views/cluster/Nodes/NodeExtensions.vue, frontend/src/views/common/NodeContextMenu.vue, internal/backend/runtime/omni/virtual/state.go
Also introduce the cluster permissions cache in the memory of the browser session.
Otherwise fetching cluster permissions will be done for each cluster machine item.
From this point, to see the updated cluster permissions, the user will just have to reload the page.
Fixes: https://github.com/siderolabs/omni/issues/1200
=> fix: do not show some menu elements for Reader users in the UI

client/pkg/omni/resources/omni/cluster.go, client/pkg/template/internal/models/cluster.go, client/pkg/template/template_test.go, client/pkg/template/testdata/cluster1-resources.yaml, client/pkg/template/testdata/cluster1.yaml, internal/backend/runtime/omni/state_validation.go
Move the cluster validations which do not require server-side information (access to resources) to a common place.
Use this new validator both from the server side validations and from the cluster templates validations.
This makes the validations consistent, resolving the inconsistency where cluster names (ID) were validated on templates but not by the server.
Closes #1198.
=> fix: make cluster validations consistent between templates and UI

hack/test/integration.sh
The latest Talemu got updated to support new infra provider schema.
As Talemu registers itself (apart from the other providers), it needs to be able to create `infra.Provider` resource, which was introduced in the latest Omni. Which was kinda chicken and egg problem as Omni needed updated Talemu for the tests to pass, that's why it had this temp override.
=> test: use latest Talemu infra provider version in the integration tests

.conform.yaml, client/pkg/access/serviceaccount.go, hack/test/integration.sh, internal/backend/runtime/omni/controllers/omni/service_account_status.go, internal/backend/runtime/omni/controllers/omni/service_account_status_test.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/migration/migrations.go
The suffix should be checked there, not prefix.
Also write the tests to verify service account status controller. Found couple more issues with the finalizers flow in the controller.
(cherry picked from commit e5d1b4b0837c3cae9a1ae2347fdc9cf71a35f4fe)
=> fix: properly detect infra provider service accounts

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, frontend/src/api/omni/specs/omni.pb.ts, internal/backend/powerstage/watcher.go, internal/backend/powerstage/watcher_test.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go, internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go, internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go, internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/backend/runtime/omni/controllers/omni/machine_status_test.go, internal/backend/runtime/omni/controllers/omni/maintenance_config_status.go, internal/backend/runtime/omni/omni.go
Power stage watcher was working by coincidence, only when waking up at the right time. This was because it was not getting notified when a machine was allocated to a cluster.
Fix this by also getting notified on `Created` events on `ClusterMachine`s. Also rework the watcher, make it testable and add a unit test for it.
Additionally: Store the agent mode info in machine status, and if it is in agent mode, skip attempting to call unsupported APIs.
Closes #1228.
=> fix: make sure `powering on` stage is correctly set on infra machines

internal/backend/runtime/omni/controllers/omni/machine_status.go
When reconciling a `MachineStatus`, we look at the `MachineStatus` field on the `MachineStatusSnapshot` resource. This field can be nil if the snapshot contains a power stage event - i.e., when the bare-metal infra provider is used, and a power status change is happened on `InfraMachineStatus`.
Use the nil-safe getter on the spec field to avoid crashing `MachineStatusController`.
Probably closes https://github.com/siderolabs/omni-infra-provider-bare-metal/issues/55 - this I believe was most likely the issue.
=> fix: fix nil dereference in machine status controller

internal/backend/runtime/omni/state.go
This should address buffer overrun on Omni restarts, when the account has >1000 machines registered.
Fixes: https://github.com/siderolabs/omni/issues/1234
=> fix: bump inmem COSI state history capacity

frontend/src/views/omni/Machines/MachineItem.vue
When the machine power state is unknown, on the UI its value is `undefined` (probably because of `omitempty`, as all the other fields with zero values are also seem to be `undefined`).
Handle this, so we show the correct power status of `Unknown` instead of `Off`.
=> fix: display unknown power state correctly on the machines screen

internal/backend/runtime/omni/controllers/omni/config_patch_cleanup.go
In the config patch cleanup controller, we falsely assumed that the resource update time was set to be the same as the creation time.
This in very rare cases caused the cleanup controller started by the runtime in the tests to prune the config patch created by the test itself, failing it sporadically.
This should fix the rare test flake we have:
```text
#66 4.431     grpc_test.go:266:
#66 4.431         	Error Trace:	/src/internal/backend/grpc/grpc_test.go:266
#66 4.431         	Error:      	Received unexpected error:
#66 4.431         	            	rpc error: code = NotFound desc = resource ConfigPatches.omni.sidero.dev(default/1@undefined) doesn't exist
#66 4.431         	Test:       	TestGrpcSuite/TestCrud
```
=> fix: check config patch creation time as well as updated on orphan check

internal/pkg/config/config.go
Previously it was `0.0.0.0:8095`. Missed that in the config rewrite.
=> fix: use `0.0.0.0:8095` as the default bind endpoint for Kubernetes

internal/backend/runtime/omni/controllers/helpers/helpers.go, internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler.go, internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler_test.go, internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
Exposed services with user-specified (explicit) prefixes had a problem with their reconciliation in the following scenario:
- service A has explicit prefix X
- service B also has explicit prefix X -> service B is marked as in error state because the prefix X is already owned by another service
- service A is updated to have a new prefix, Y
- service B is still in the error state, until a new reconciliation is triggered (e.g., a service C is introduced or any other change)
Fix this by removing the freed prefix (X) from the "used prefixes" list during reconciliation. Add a unit test for it.
Rework the `exposedservice.Reconciler` to make it testable by simplifying it.
=> fix: fix exposed service prefix conflict resolution

internal/pkg/config/config_test.go, internal/pkg/config/services.go, internal/pkg/config/testdata/config-no-tls-certs.yaml
- With the config rewrite, it is possible to pass cert and key file paths for the Kubernetes Proxy component specifically (only to the Kubernetes proxy), just like all the other http server components. These fields are marked as required and we validate them.
- They can only be passed through the config file, there is no command line arg defined for those.
- When they are not defined, they will fall back to the `--cert` and `--key` passed to Omni itself - to the whole Omni API cert and key.
- This is wrong, as Omni might be run without `--cert` and `--key` flags, e.g., if it is running behind a reverse proxt that handling TLS termination.
Fix this by removing the required validation annotation, and add a test for it.
=> fix: remove `required` config validation from k8s proxy cert and key

cmd/omni/cmd/cmd.go, internal/pkg/config/config.go, internal/pkg/config/logs.go, internal/pkg/config/storage.go
- Make sure to write the account ID passed via `--account-id` into the correct struct so it will land into the final config as expected.
- Add `merge:"replace"` directives on a few `[]string` fields in the config, so that when the user sets overrides, they won't be merged with the base/default values. This is specifically important for the etcd endpoints, as with the default config merge behavior, we end up with an endpoint set of default + command-line args, like: `["http://localhost:2379","https://omni-etcd-0.omni-etcd.svc:2379","https://omni-etcd-1.omni-etcd.svc:2379","https://omni-etcd-2.omni-etcd.svc:2379"]`.
=> fix: do more fixes on config backward-compatibility

internal/backend/runtime/omni/controllers/omni/infra_machine.go, internal/integration/blocks_test.go, internal/integration/cluster_test.go, internal/integration/integration_test.go, internal/integration/suites_test.go, internal/integration/talos_test.go
Always save it, not only in DestroyCluster. It is not used as finalizer anymore.
=> test: save a support bundle when a test suite has failed

.github/workflows/ci.yaml, .github/workflows/e2e-omni-upgrade-cron.yaml, .github/workflows/slack-notify.yaml, .kres.yaml, hack/test/integration.sh, internal/integration/integration_test.go, internal/integration/omni_upgrade_test.go, internal/integration/suites_test.go
CI will run integration tests from the previous release first, then run them from the current commit using other set of tests.
Fixes: https://github.com/siderolabs/omni/issues/1132
=> test: test updating from old Omni version to the current

frontend/src/views/omni/Clusters/Management/ClusterCreate.vue, frontend/src/views/omni/Clusters/Management/ClusterScale.vue, frontend/src/views/omni/Machines/MachineItem.vue, internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go, internal/backend/runtime/omni/controllers/omni/machine_status.go, internal/integration/omni_upgrade_test.go
We read the block disks on the machine status if there is a system disk to detect if Talos is installed on the machine. Based on this, we allow or disallow maintenance updates.
This value might be stale when the bare-metal provider is used, as it powers off the machines when they are idle, and this causes their hw information to not be updated. So, the disk might be wiped, but machine status poller might not catch the change in the block devices before it is powered off.
Instead, take the `installed` flag on the infra.MachineStatus resource as the source of truth for the machines managed by the bare metal infra provider. Update the `installed` label based on that.
Change the logic in the frontend for installation detection to use this label instead of checking block devices directly.
=> fix: correctly detect installation status for bare-metal machines

go.mod, go.sum
The fix properly propagates the `xmlns` attributes from the parent elements to the children.
Fusion Auth doesn't set `xmlns` attribute on the `<Assertion>` element, but it's set on the `<Response>` which is the parent element.
=> fix: update SAML library to the forked version with the ACS parser fix

Dockerfile, internal/backend/grpc/configs_test.go, internal/backend/grpc/grpc_test.go, internal/backend/runtime/omni/controllers/omni/omni_test.go, internal/backend/runtime/omni/migration/migration_test.go, internal/backend/runtime/omni/omni_test.go, internal/backend/runtime/omni/talosconfig_test.go, internal/backend/runtime/talos/clients_test.go, internal/pkg/siderolink/provision_test.go, internal/pkg/siderolink/siderolink_test.go
Our unit test logs are too verbose/excessive because:
- COSI runtime writes a lot of `reconcile succeeded` logs
- migration tests were too spammy
This caused the logs to get clipped by docker/buildx in the CI:
```
[output clipped, log limit 2MiB reached]
```
and resulted in mysterious test failures without the failure reason being printed.
With these changes we pull our unit test logs a bit below the 2MiB limit (1.7MiB).
=> test: reduce the log verbosity in unit tests

internal/backend/runtime/omni/infraprovider/state.go, internal/backend/runtime/omni/infraprovider/state_test.go
Infra provider state is a bit special - when an infra provider attempts an operation on a resource, we do an authorization check: is the provider allowed to be able to access this resource at all.
For the resources in their dedicated namespaces (e.g., `infra-provider:<id-of-the-provider>`), it is easy, but for the ones in common namespaces (e.g., `infra-provider`), we filter the returned resources.
When doing this filtering, we were wrongly not passing through the `state.Noop` events.
This caused the bookmark information to not be delivered to the clients, which broke the reconnection logic on the affected clients (infra providers).
Fix this and refactor the state to unify the filtering logic into common functions.
=> fix: do not filter out noop events in the infra provider state

client/pkg/infra/controllers/provision.go, client/pkg/infra/infra.go, client/pkg/infra/infra_test.go, client/pkg/jointoken/jointoken.go, client/pkg/jointoken/jointoken_test.go, client/pkg/siderolink/siderolink.go, internal/backend/runtime/omni/controllers/omni/provider_join_config_test.go, internal/pkg/siderolink/provision.go, internal/pkg/siderolink/provision_test.go
This can help to support compatibility for the newer providers vs older Omni versions.
Also support legacy flow in the infra providers common library: if the provider join config doesn't exist, fallback to using `ConnectionParams` along with join token version 1.
=> fix: allow encoding join tokens using v1 version

client/pkg/siderolink/siderolink.go, client/pkg/siderolink/siderolink_test.go
Extra docs are passed as the optional args array.
=> chore: support encoding extra docs in `siderolink.RenderJoinConfig`

internal/backend/dns/service.go
We can probably tolerate it being empty in the Talos request proxying. Otherwise the behavior is confusing: the node is connected, but it's not possible to reach it with `talosctl` using the node UUID.
=> fix: ignore `MachineStatus` having no TalosVersion in DNS service

internal/backend/runtime/omni/migration/migrations.go, internal/integration/integration_test.go, internal/pkg/config/config.go
This is going to be enabled for the upgrade tests when we run the previous `integration-test` executable.
Otherwise new fields introduced in the config mess it up.
=> test: allow ignoring unknown config fields in the integration test

client/pkg/omnictl/config/config.go
Fixes: https://github.com/siderolabs/omni/issues/683
=> fix: properly handle empty configs in `omnictl config merge` CLI command

internal/backend/runtime/omni/controllers/omni/link_cleanup.go, internal/backend/runtime/omni/controllers/omni/link_cleanup_test.go
Add MachineLabels to the list of resources to be cleaned up on Link deletion. Add a simple unit test for the cleanup controller.
Closes #1331.
=> fix: remove MachineLabels when a Link is removed

.dockerignore, Dockerfile
`bun.lock` was not being copied over to the container, so inside the container dependencies were being quietly updated. In this instance, typescript was quietly updated from `5.8.3` to `5.9` which introduces a [change](https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/) that resulted in this error during build:
<details>
<summary>
Output
</summary>
```
=> ERROR [omni frontend 1/3] RUN --mount=type=cache,target=/src/node_modules,id=omni/src/node_modules bun run build ${JS_BUILD_ARGS}                                            1.3s
------
> [omni frontend 1/3] RUN --mount=type=cache,target=/src/node_modules,id=omni/src/node_modules bun run build ${JS_BUILD_ARGS}:
0.069 $ vue-tsc && vite build
1.129 src/methods/index.ts(144,53): error TS2345: Argument of type …
```
=> fix: install frontend dependencies from lockfile

frontend/src/views/omni/Clusters/Management/ClusterCreate.vue, frontend/src/views/omni/Clusters/Management/ClusterScale.vue, internal/backend/runtime/omni/state_validation.go
Do not enforce major.minor version check for talos on machine allocation if the machine is running in agent mode
Fixes #1358
=> fix: stop enforcing talos version check on machine allocation

internal/backend/grpc/serviceaccount.go, internal/integration/auth_test.go, internal/pkg/auth/serviceaccount/serviceaccount.go
Prevent service account creation if name is already in use
=> fix: prevent service account creation if name is already in use

frontend/.gitignore, frontend/.vscode/extensions.json, frontend/.vscode/settings.json
Commit some recommended extensions and settings for frontend in vscode to the repository. After installing the recommended extensions, saving the file should automatically fix any style/code issues (if they are auto-fixable).
Can still run `npm run lint` to check for errors and/or `npm run lint:fix` to fix them. There will be some warning output for now for some small issues I haven't dealt with yet.
Will need to locally install node 22.18 or newer for the npm commands and/or extensions (particularly eslint, needs a funny flag for now that only that node supports).
Related:
- https://github.com/siderolabs/kres/pull/547
=> chore: commit vscode settings for frontend

cmd/omni/cmd/cmd.go, cmd/omni/pkg/app/app.go, go.mod, go.sum, hack/test/integration.sh, internal/backend/grpc/grpc_test.go, internal/backend/runtime/omni/omni.go, internal/backend/runtime/omni/omni_test.go, internal/backend/runtime/omni/talosconfig_test.go, internal/backend/services/workloadproxy/reconciler.go, internal/backend/services/workloadproxy/reconciler_test.go, internal/backend/workloadproxy/lb/lazy.go, internal/backend/workloadproxy/lb/lb.go, internal/backend/workloadproxy/lb/probe_all.go, internal/backend/workloadproxy/lb/probe_windows.go, internal/pkg/config/config.go, internal/pkg/config/services.go
- Add jitter to the exposed service health checks, so they spread evenly even when the services are all reconciled at the exact same time.
- Add the "lazy" logic to the current workload proxy health checks by wrapping the "regular" LB with a lazy LB wrapper. With this, we gain:
- Health checks are started only when an exposed service is attempted to be accessed ("dialed").
- They are stopped after 5 minutes of inactivity.
Depends on siderolabs/go-loadbalancer#24.
Part of #1255.
=> feat: add jitter and lazy health checks to exposed services

frontend/eslint.config.ts, frontend/src/components/common/TInput/TInput.vue
Use vue specific rules for dot-notation and eqeqeq which extend the rules to inside templates
=> chore: use vue specific rules for dot-notation and eqeqeq

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, client/api/omni/specs/virtual.pb.go, client/api/omni/specs/virtual.proto, client/api/omni/specs/virtual_vtproto.pb.go, cmd/omni/cmd/cmd.go, frontend/package-lock.json, frontend/package.json, frontend/src/api/omni/specs/omni.pb.ts, frontend/src/api/omni/specs/virtual.pb.ts, frontend/src/methods/auth.ts, frontend/src/methods/features.ts, frontend/src/router/index.ts, internal/backend/runtime/omni/virtual/state.go, internal/frontend/handler.go, internal/pkg/config/config.go, internal/pkg/features/features.go
Omni now has `--user-pilot-app-token` flag. When set it will enable `Userpilot` integration in the UI.
=> feat: support Userpilot reports

frontend/src/methods/auth.ts, frontend/src/views/common/NodeContextMenu.vue
Fixes a console warning about an invalid watch value being sent to vue.
```
[Vue warn]: Invalid watch source:  {value: 'talos-default-1'}
A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. 
at <NodeContextMenu cluster-machine-status=...
```
=> fix: console warning about invalid watch value

frontend/src/App.vue, frontend/src/components/common/UserConsent/UserConsent.vue, frontend/src/methods/auth.ts, frontend/src/methods/features.ts
The form allows to agree or decline data collection. When declined UserPilot library is not activated.
Tracker state is saved in the local storage.
Fixes: https://github.com/siderolabs/omni/issues/1446
=> feat: implement user consent form for the `UserPilot`

frontend/src/views/omni/Auth/Authenticate.vue
There was a missing `break` that was making it fall through to the SAML and OIDC implementations.
=> fix: fix switch user button for Auth0

client/api/omni/specs/omni.pb.go, client/api/omni/specs/omni.proto, client/api/omni/specs/omni_vtproto.pb.go, frontend/src/api/omni/specs/omni.pb.ts, internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go, internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
Do not include the comments to the generated ClusterMachineConfig to prevent triggering noop machine updates caused by changes on machine config comments
Fixes #1581
=> chore: strip comments from generated ClusterMachineConfig

hack/release.toml, internal/backend/grpc/management.go
If `grant-type=authcode-keyboard` is requested.
Fixes: https://github.com/siderolabs/omni/issues/1476
> [!Note]
> configs generated with the new Omni and `authcode-keyboard`
> enabled won't work for `oidc-login` below `v1.33`. See https://github.com/int128/kubelogin/pull/1263
=> fix: add `oidc-redirect-url` arg to the generated kubeconfigs

frontend/src/views/cluster/ClusterMachines/ClusterMachines.vue, frontend/src/views/cluster/ClusterMachines/MachineRequest.vue, frontend/src/views/cluster/ClusterMachines/MachineSet.vue, frontend/src/views/omni/Clusters/ClusterItem.vue, frontend/src/views/omni/Clusters/Clusters.stories.ts, frontend/src/views/omni/Clusters/Clusters.vue
Fix the alignment of provisioning machines on the clusters page. Also refactored some `Watch` into `useWatch`
Fixes #1659 
<table>
<tr>
<th>Before</th>
<td><img width="1020" height="360" alt="image" src="https://github.com/user-attachments/assets/967849be-e469-44cc-ace6-f7dcc01354a2" /></td>
</tr>
<tr>
<th>After</th>
<td><img width="1018" height="307" alt="image" src="https://github.com/user-attachments/assets/b1edee3d-0503-4d4d-872e-00545017f430" /></td>
</tr>
</table>
=> fix(frontend): fix alignment of provisioning machines

deploy/helm/README.md
Deploying it this way results in a HTTP 503 error. Might prevent others having to fix it themselves.
=> Fix: Typo in Helm chart readme service name for API Ingress example
